Dockerfile
README.md

Points of improvements:
* find a small docker image to be used as its base.
* push this image to docker hub so people can use it remotely without even cloning this repo.
* fix the python warning https://github.com/matplotlib/matplotlib/issues/5836 .

Adds support for docker usage

---

Dockerfile
README.md

Adds docker support for all the executables

---

README.md

Hi, I have added installation and usage instruction for libvmaf so that it becomes easier for users to install and use the library.

Installation and usage instructions for libvmaf

---

python/src/vmaf/config.py

Added a more helpful error message when an import goes wrong when using the vmaf tool.

Added helpful error message for VmafExternalConfig

---

README.md

Signed-off-by: Werner Robitza <werner.robitza@gmail.com>

fix documentation for Homebrew python, fixes #161

---

Dockerfile

* Due to a prompt asking for location information during build, the
progress would halt. Set UTC for timezone.
* Changed method of installing pip. There was an error from using
easy_install.
* Changed RUN cd to WORKDIR.
* Since vmaf is in $PATH, reset the WORKDIR to /root/

Updated Dockerfile to build successfully

---

wrapper/src/combo.c

Fix visual studio compile error

Fix vs compile error with a MULTI_THREADING option (#200)

---

python/src/vmaf/core/train_test_model.py

Helpful to supply additional information to the training process, if needed.

Add kwargs internally to training method.

---

README.md
matlab/STMAD_2011_MatlabCode/Example.m
python/script/run_testing.py
python/src/vmaf/core/matlab_feature_extractor.py
python/src/vmaf/core/matlab_quality_runner.py
resource/doc/matlab_usage.md

A couple of researchers have expressed interest in using the Matlab portion of the repository. Adding some documentation and fixing some relevant bugs.

Matlab dev

---

feature/src/ansnr.c

the default).
We measured that we're spending most of our time doing the 2D convolution.
This makes compute_ansnr() ~1.8x faster.
In addition, reuse the filtd temporary buffer. This makes the function
use 2/3 of the original memory.

Avoid dis-filtering ref when not needed (!ANSNR_OPT_NORMALIZE, which is

---

feature/src/common/frame.c
feature/src/common/frame.h
wrapper/src/libvmaf.h
wrapper/src/main.cpp

Print progress in vmafossexec

---

wrapper/src/main.cpp

Use stat struct instead of ftell to retrieve the file size

---

wrapper/Makefile
wrapper/libvmaf.pc.in

Templatize libvmaf.pc

---

Dockerfile

docker build broke after meson build added
this commit is to fix docker build

fix docker image after using meson for building

---

resource/doc/libvmaf.md

I noticed the links are not good anymore.
Not sure about other instructions on that page since I haven't (yet) tried to build and run the examples.

📝libvmaf doc: fix links

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/test/meson.build
libvmaf/test/test_feature_extractor.c

Here's the initial implementation of `VmafFeatureExtractor`.

libvmaf: implement VmafFeatureExtractor

---

resource/doc/vmafossexec.md

vmafossexec is now built using meson instead of make

Update vmafossexec build instruction

---

.dockerignore
Dockerfile

Add ignore pattern for unneeded directories, and copy the source code, instead
of cloning the repo again

improve Dockerfile

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/libvmaf.rc.c
libvmaf/test/test_feature_extractor.c

implements the `VmafFeatureExtractorContext` which is the runner defined by `VmafFeatureExtractor`.

libvmaf: implement VmafFeatureExtractorContext

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_vif.c
libvmaf/src/libvmaf.rc.c
libvmaf/src/model.h
libvmaf/src/predict.c
libvmaf/src/unpickle.cpp
libvmaf/tools/vmaf.c

Prediction is working now and seems accurate.

libvmaf: implement vmaf_score_pooled

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/feature/float_motion.c
libvmaf/src/libvmaf.rc.c
libvmaf/src/output.c
libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

Adds support for subsampled feature extraction and score computation.

libvmaf: add support for subsampled score computation

---

libvmaf/src/libvmaf.rc.c

This adds support for mean, harmonic mean, and min pooling methods.

libvmaf/vmaf_score_pooled: support all pooling methods

---

.travis.yml

fix macos build on travis

---

libvmaf/doc/meson.build
libvmaf/src/feature/feature_extractor.h

Add some docs for the VmafFeatureExtractor private api.

VmafFeatureExtractor: add api docs

---

libvmaf/src/meson.build

Add soname to libvmaf

---

README.md

Currently points to the libvmaf job at https://github.com/Netflix/vmaf/actions?query=workflow%3Alibvmaf

README: Add Github Actions status badge

---

libvmaf/src/feature/alias.c
libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/integer_motion.c
libvmaf/src/meson.build
libvmaf/tools/vmaf.c

Rebase and cleanup of #536. 60 less lines of code, ~3x faster, exact same output.

Integer Motion Cleanup and Rebase

---

libvmaf/src/libvmaf.rc.c

libvmaf_rc: fix memory leak when multithreaded and subsample > 1

---

libvmaf/src/feature/alias.c
libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/integer_vif.c
libvmaf/src/feature/vif_buffer.h
libvmaf/src/meson.build

Co-authored-by: IttiamVijayakumarGR <62744303+IttiamVijayakumarGR@users.noreply.github.com>

libvmaf: implement integer VIF

---

libvmaf/src/meson.build

Add rev_target to libvmaf_rc for proper building order

---

libvmaf/src/feature/alias.c
libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/integer_adm.c
libvmaf/src/meson.build

Cleaned-up and rebased version of #551.

libvmaf: implement fixed-point adm

---

.travis.yml

Travis: Add Fail-able ARM job and fix clang issues 

---

libvmaf/src/feature/integer_motion.c

No impact on the final score, changed just for consistency.

Fix inverted height and width

---

README.md

*fixed typo-> "interoperrability" in the 'line 16'.
*reformatted document.
and added other details.

reformatted and rectified document vmaf/README.md

---

libvmaf/src/unpickle.cpp

We have a few published test models with no normalization. This commit fixes the deserialization of those models.

unpickle: support deserialization of models with VMAF_MODEL_NORMALIZATION_TYPE_NONE

---

resource/doc/ffmpeg.md

As said in #658 that it would be a better idea to make a header for all the external resources.
Now other people might be able to add their ideas too 👍

Added external resources to vmaf for ffmpeg guide

---

libvmaf/src/feature/x86/motion_avx2.c
libvmaf/src/ref.h
libvmaf/test/test_picture.c

This fixes build error on macOS Catalina

Fix build error on macOS Catalina

---

resource/doc/ffmpeg.md

Adds some notes about Windows and paths passed to `model_path` #413

Doc/ffmpeg.md: Add note about using another folder and also for Windows

---

python/test/perf_metric_test.py
python/vmaf/core/perf_metric.py

and adding a corresponding test

Fixing the perf_metric for a single entry list input 

---

.github/workflows/ffmpeg.yml
.github/workflows/libvmaf.yml

WIP, our MacOS CI runners are all failing at the `brew` stage. Trying to debug and fix.

Fix, MacOS CI runners are all failing at the brew stage

---

README.md

This build has been migrated to travis-ci.com as per their [recommendation](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom).

Update Build Status Location

---

.github/workflows/ffmpeg.yml
.github/workflows/libvmaf.yml

Attempted stopgap to get CI building again.

Github Actions: fix CI

---

libvmaf/src/feature/integer_psnr.c

This PR rewrites the PSNR feature extractor to use integer types during the SSE calculation and removes the scale factor inherited from the floating point version. The results are still exact to what they were before, but now the computation is roughly twice as fast as float_psnr.
```
#FLOAT PSNR
real         3.37
user         2.74
sys          0.62
#INTEGER PSNR
real         1.48
user         0.80
sys          0.66
```
This PR also add parameters for `enable_mse` for dumping mse values, as well as `reduced_hbd_peak` which reduces the peak value in HBD content to align with max value of scaled 8-bit content. This is a requirement for the upcoming AOM CTC. Both of these new parameters are turned off by default. i.e. the normal behavior does not change.

libvmaf/psnr: rewrite using integer types, 2x speedup

---

.github/workflows/libvmaf.yml
.github/workflows/windows.yml

This PR adds a upload artifact for the linux and mac Github actions builds.

ci/actions: upload linux/macos artifact

---

libvmaf/tools/vmaf.c

Also does not print version when quiet is selected

Do not display VMAF if quiet and output are set

---

.github/workflows/ffmpeg.yml

Fixes the current macOS issues

github: remove workaround for macOS issues

---

.github/workflows/libvmaf.yml
.travis.yml

This PR adds the Python tox tests to the Github actions CI. See #774 for background.

actions: run tox tests

---

.github/workflows/ffmpeg.yml

Hopefully this solves the failing macos ffmpeg build. It's a brew issue.

actions: avoid brew problem

---

resource/doc/aom_ctc.md

Initial import of the AOM CTC documentation.

docs: initial import of aom_ctc.md

---

resource/doc/external_resource.md
resource/doc/ffmpeg.md

Useful for those who are too lazy to compile FFmpeg.

Add links to FFmpeg binaries that support libvmaf.

---

libvmaf/src/model.c

Addresses the mismatch from issue #823.

libvmaf/model: address builtin 4k model mismatch (#823)

---

python/test/feature_extractor_test.py
python/vmaf/core/feature_extractor.py

Revert "Remove pypsnr fex."

---

libvmaf/src/read_json_model.c

Signed-off-by: akarin <AkarinVS@users.noreply.github.com>

libvmaf: fix FILE* leaks when reading model json

---

libvmaf/src/output.c

This PR fixes `inf` and `NaN` values present in the output JSON, which are not valid JSON syntax. In the cases of `inf`/`NaN`, JSON value `null` is printed. For an example, see the `psnr_hvs` fields in the log below. A question I still have is if `null` is good enough to capture both `NaN` or `inf`, or if these should somehow be differentiated?
Fixes #215.
```json
{
"version": "84ffd67f",
"frames": [{
"frameNum": 0,
"metrics": {
"integer_adm2": 1.000001,
"integer_adm_scale0": 1.000002,
"integer_adm_scale1": 1.000000,
"integer_adm_scale2": 1.000001,
"integer_adm_scale3": 1.000000,
"integer_motion2": 0.000000,
"integer_motion": 0.000000,
"integer_vif_scale0": 0.999997,
"integer_vif_scale1": 0.999983,
"integer_vif_scale2": 0.999983,
"integer_vif_scale3": 0.999984,
"psnr_y": 60.000000, …
```

libvmaf/output: fix inf/NaN values in JSON output

---

libvmaf/include/libvmaf/picture.h
libvmaf/src/picture.c

Adding support for yuv400p VmafPicture type to allow for single component processing

Add support for yuv400p VmafPicture type

---

Dockerfile
Makefile
resource/doc/docker.md

* The current docker image build failed. I fixed the build by following the instructions in the READMEs
* Added an entrypoint to the docker image to run it with `run_vmaf` by default
* Updated the documentation for the docker image

Docker: fix image build

---

libvmaf/src/feature/cambi.c
python/test/cambi_test.py
python/test/testutil.py

Bugfix for CAMBI 10-bit input.
Co-author: @nilfm

Fix memcpy issue for CAMBI 10-bit inputs

---

Makefile

Revert "Add install vmaf to make install."

---

libvmaf/tools/vmaf.c

tools/vmaf: clean up frame_skip logic

---

libvmaf/meson.build

libvmaf: bump meson_version

---

libvmaf/README.md

Also the doc needs a version bump.
Isse: https://github.com/Netflix/vmaf/issues/1092

Bump meson version also in docs

---

libvmaf/src/feature/ciede.c

The `close` implementation in `ciede.c` was unreffing a picture that didn't belong to it. This was, in some cases such as the one described in #1103, corrupting memory and causing an invalid free error.
This PR eliminates the duplicate unrefs.

[fix #1103] remove duplicate unreffing in ciede.c

---

libvmaf/src/libvmaf.c

I noticed some problems when running a CUDA build with multithreading enabled. Even if not CUDA extractors are enabled multithreading is disabled. 
I tested with below command and appended a matrix of options:
`--feature psnr --feature float_ssim` - CPU only extractors 
`--threads $THREADS` - THREADS [0, 1, 16]
`--gpumask $CU_DISABLED` - CU_DISABLED [0, 1]
```
./libvmaf/build/tools/vmaf --reference $file_ref --distorted $file_dis \
--width $var_width --height $var_height --pixel_format $var_pfmt --bitdepth $var_bpc \
-o $file2 --json 
```
Following errors occured:
- CUDA build did not use any mutlithreading even with CUDA disabled
- mixing CUDA+CPU extractors forces to run in a single thread

Fix: CUDA+multithreading

---

libvmaf/src/feature/vif.c
libvmaf/src/feature/vif_tools.c

* remove two unnecessary buffers
* uniformize whitespace
* simplify the logic to index kernelscale

Minor improvements to float_vif

---

python/vmaf/tools/reader.py

This commit introduces a new function convert_format that handles the conversion of y, u, and v based on the bit depth. This change helps to reduce code repetition in the reader.py file. The bit depth is determined based on the conditions and the convert_format function is used to convert y, u, and v. This makes the code more maintainable and easier to understand.

refactor: format conversion to reduce code repetition

---

libvmaf/src/feature/arm64/vif_neon.c
libvmaf/src/feature/integer_motion.c
libvmaf/src/feature/integer_motion.h
libvmaf/src/feature/integer_vif.c
libvmaf/src/feature/integer_vif.h
libvmaf/src/feature/x86/motion_avx2.c
libvmaf/src/feature/x86/motion_avx512.c
libvmaf/src/feature/x86/vif_avx2.c
libvmaf/src/feature/x86/vif_avx512.c
libvmaf/src/predict.c

Need to run some tests to make sure this doesn't change anything.

Fix remaining warnings

---

python/pyproject.toml
python/requirements.txt
python/setup.py
python/tox.ini

setup.py: use setuptools, modernize cython import

---

libvmaf/include/libvmaf/libvmaf.h

Addresses the comment at #1214

Add link to n_subsample observation on usage page

---

python/vmaf/core/asset.py
python/vmaf/core/cross_validation.py
python/vmaf/core/executor.py
python/vmaf/core/feature_assembler.py
python/vmaf/core/feature_extractor.py
python/vmaf/core/local_explainer.py
python/vmaf/core/matlab_feature_extractor.py
python/vmaf/core/matlab_quality_runner.py
python/vmaf/core/mixin.py
python/vmaf/core/niqe_train_test_model.py
python/vmaf/core/nn_train_test_model.py
python/vmaf/core/noref_feature_extractor.py
python/vmaf/core/perf_metric.py
python/vmaf/core/quality_runner.py
python/vmaf/core/quality_runner_extra.py
python/vmaf/core/raw_extractor.py
python/vmaf/core/result.py
python/vmaf/core/result_store.py
python/vmaf/core/train_test_model.py

Style and typo fixes following PyCharm's linter, and a minor bug fix in an assertion

python: misc fixes

---

.github/workflows/libvmaf.yml
python/tox.ini

.github/workflows/libvmaf.yml: upgrade python version to 3.11
