Xcode/vmaf_xcode.xcodeproj/project.pbxproj
Xcode/vmaf_xcode.xcodeproj/project.xcworkspace/contents.xcworkspacedata
feature/src/common/alignment.h

The Xcode project file is created for testing and debugging.
This project can build several binaries for macOS Sierra, including vmaf, mssim, ssim, psnr and moment.
Tested in macOS Sierra.

Create Xcode project workspace for development

---

python/src/vmaf/core/vqm_quality_runner.py

Using yuv422p10le does not provide reliable results.

Update VqmQualityRunner to use yuyv422 as intermediate input to VQM.

---

.travis.yml
Makefile
README.md
wrapper/Makefile
wrapper/libvmaf.pc

Hi, added **pkg-config** for libvmaf to allow external programs to query libvmaf and to check if it's installed.
Also merged **make lib** with **make** so creation of both **libvmaf.a** and **vmafossexec**  takes place on running **make**.
Linked vmafossexec to libvmaf.a , so vmaf also uses the libvmaf library. Updated readme.
I am ready to revert any changes that are not consistent.

pkg-config for libvmaf

---

wrapper/wrapper.vcxproj
wrapper/wrapper.vcxproj.filters

This temporarily fixes the Visual Studio (2015 and 2017) builds until @li-zhi is done with the code structure changes.
#107

Temporary fix Visual Studio builds

---

Dockerfile
README.md

This shrinks the size of the resulting Docker image from around 3.5 GB to 1.5 GB by removing unneeded dependencies (e.g. texlive).
Tests still pass.
The `$(PWD)` command has been changed to `$(pwd)` – the former doesn't work as `$PWD` is an environment variable whereas `pwd` is a shell builtin.

Remove unneeded dependencies in Dockerfile, fixes #115

---

feature/src/common/alloc.c

The current guard in feature/src/common/alloc.c only checks for
a MSVC environment before selecting a POSIX aligned malloc function.
This causes MinGW/GCC compilations of the library & vmafossexec to fail.
Patch adds a check for MinGW.

MinGW support

---

.gitattributes

Force .pkl and .model files to retain LF line-ending. Required for use on Windows where model files would otherwise be checked out as CRLF which VMAF's parser doesn't handle.

 Add .gitattributes

---

README.md

For the first step to support python3, I modify code snippets on README. It just replace a print statement with the function (these changes are also compatible with python2).
This PR is related to https://github.com/Netflix/vmaf/issues/128

Replace a print statement with the function on README

---

ptools/fdtools.h
ptools/midassocket.cc
ptools/midassocket.h
ptools/p2common.h

ptools doesn't build on MinGW as *nix socket headers are included. This patch selects Windows headers for MinGW builds.

Allow MinGW compilation of ptools

---

ptools/Makefile

On Windows, symlinks are checkout as regular files. This breaks ptools compilation.

Replace with regular Makefile that includes active Makefile

---

wrapper/src/combo.c
wrapper/src/debug.h
wrapper/src/vmaf.cpp

Fix a thread lock situation detected in vmafossexec (at least when running in MacOS). It happens quite infrequently (1 of 30 approx) but it is there and is easy to reproduce for longer files. This PR modifies `combo_threadfunc` function of `combo.c` to remove `pthread_mutex_unlock` operations that were done over an already unlocked mutex. After applying this change I couldn't reproduce the thread lock anymore.
I took advantage of this change to create a macro for printing progress while keeping the possibility of activating/deactivating it through a preprocessor define (`PRINT_PROGRESS`). Just to keep code easy to read.

Fix thread lock situation

---

feature/src/adm_tools.h
feature/src/common/blur_array.c
feature/src/common/file_io.h
feature/src/common/frame.c
feature/src/psnr_tools.c
wrapper/src/combo.c

I'm making VMAF run in iPhone & Android using LLVM.
First of all, I fix implicit declarations of functions to follow C99.

Fix implicit declarations of functions

---

wrapper/src/svm.cpp

This problem is occur intermittently(using libvmaf.a) when start vmaf in multi-thread at the same time. 
global pointer 'char* line' can accessed at the same time in each thread.
I moved this global pointer to local pointer.

Bug fixed. When start vmaf in multi-thread at the same time.

---

wrapper/Makefile

While using libvmaf, the following warnings resulted in segmentation fault in (line 634) wrapper/src/combo.c
To build static library:
Command : sudo make install
Makefile:133: warning: overriding recipe for target '/home/vmaf/wrapper/obj/psnr.o'
Makefile:109: warning: ignoring old recipe for target '/home/vmaf/wrapper/obj/psnr.o'
psnr.o is generated twice.
This solves the issue #247

Remove reduntant object file generation for psnr

---

CHANGELOG.md
VERSION
python/src/vmaf/core/quality_runner.py
python/test/vmafossexec_test.py
wrapper/libvmaf.pc
wrapper/src/vmaf.cpp
wrapper/src/vmaf.h

Changes to the C++ code so that the output of vmafossexec in xml and json format reports the per bootstrap model scores.

Output per bootstrap model scores in vmafossexec.

---

wrapper/src/combo.c

After building the project, there are some errors executing vmafossexec (pop up windows saying variable is used without being initialized. A window per each processor or thread), it is required to ignore them so that the threads continue working. Not sure the right initialization is true or false but now it works.

fix w10 error with using uninitialized offset_flag variable

---

wrapper/src/vmaf.cpp

1. Report aggregate CI scores in vmafossexec. Also write pool method to the xml log when it's specified.
2. Fix empty model name in log on Windows. Windows users may also use forward slashes besides back slahes in file path. Looking for only back slashes results in an empty string being returned when Windows users type forward slashes in the file path.

Report aggregate CI scores and fix empty model name in log

---

README.md
appveyor.yml
resource/doc/BuildForWindows.md

This PR adds an [AppVeyor configuration](https://ci.appveyor.com/project/EwoutH/vmaf/history) that produces automated Windows builds using Visual Studio 2017. 
For optimal integration AppVeyor needs to be [enabled](https://github.com/marketplace/appveyor) on the GitHub marketplace.
All files in the `x64/release` folder are uploaded to AppVeyor as artifacts. In a future PR I will also add a deploy function to automatically upload artifacts to GitHub Releases ([example](https://github.com/EwoutH/vmaf/releases)).

Add automated Windows builds with AppVeyor 

---

wrapper/src/combo.c

Used the command:
./vmafossexec yuv420p 1920 1080 \
~/Videos/1920_1080_100fames.yuv  \
~/Videos/1920_1080_100fames.yuv \
../model/vmaf_v0.6.1.pkl \
--thread 100
can reproduce this issue when CPU cores > 128(MAX_NUM_THREADS)/3.
fix #319
Signed-off-by: Jun Zhao <barryjzhao@tencent.com>

wrapper/src/combo: Check the array size to avoid init error.

---

wrapper/src/main.cpp

I got stuck for a second because of this incorrect label in the error message. Hopefully this will help others!

errors: update name of file for failed dis_path fopen

---

.travis.yml

- Updates build environment to Ubuntu 18.04
- Uses Python 3.7 instead of 3.6

Travis CI: Update to Ubuntu 18.04, use Python 3.7

---

wrapper/src/vmaf.cpp

Small change, just removed a few printf statements. It’s completely worthless when there are multiple instances running in parallel. Also when used VIA ffmpeg it can’t be suppressed via `-loglevel` parameter.

Removed unsuppressable printf statements.

---

meson.build
wrapper/src/libvmaf.h
wrapper/src/vmaf.h

I am working on VMAF integration in GStreamer.
I wrote a meson.build file to build libvmaf and vmafossexec through the Meson Build system.
Also in this patch, I moved the VmafException class to libvmaf.h, because earlier it was not possible to catch VmafException without importing vmaf.h to code which uses *VmafQualityRunner.

Add meson.build file and move VmafException definition from vmaf.h to libvmaf.h

---

src/libvmaf/Makefile

make install was failing since make couldn't find `../model` since it was two levels up. The travis-ci was not reporting the `sudo make install` as failing
Fixes m-ab-s/media-autobuild_suite#1418

libvmaf/Makefile: Add one more .. to model

---

resource/doc/VMAF_Python_library.md

This adds the `ninja` dependency for in the brew step and the `meson` package for Python in the macOS instructions. They make it is possible to run `make` in the VMAF repository. The `meson` package requires Python 3.5.2 or greater, which is why it is using `pip3`. This is meant to solve #387.

Update macOS instructions to include ninja and meson

---

libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/test/meson.build
libvmaf/test/test_feature_collector.c

This adds a new internal struct `VmafFeatureCollector`, as well as an API for interacting with it. The  purpose of this is to collect extracted features on a per frame basis. See `feature_collector.h` and `test_feature_collector_init_append_and_destroy` for usage.
`VmafFeatureCollector` has the following attributes:
- Hold scores for an extracted feature with any `feature_name`
- Thread safe
- OOO insertion, for feature extraction parallelism on a frame level
- Avoid this mess: https://github.com/Netflix/vmaf/blob/master/libvmaf/src/combo.h#L40-L63
- Add a new feature extractor to `libvmaf` with no internal changes.
I've marked this as **WIP** for now, since I don't exactly know when the best time to integrate it is. Also there still needs to be an API to get scores out from the …

[WIP] libvmaf: add VmafFeatureCollector

---

libvmaf/src/third_party/ptools/fdtools.h

Breaks mingw-w64 builds on case sensitive systems

fdtools: de-capitalize winsock2.h

---

libvmaf/src/meson.build

FFmpeg configuration on current master branches fails since pkg-config isn't giving `${prefix}/include/libvmaf` to find libvmaf.h
Changes Cflags line in libvmaf.pc file from
`Cflags: -I${includedir}`
to
`Cflags: -I${includedir}/libvmaf`

pkg-config: Add libvmaf as a subdir to actually point to the correct includedir

---

libvmaf/include/libvmaf/model.h
libvmaf/src/model.c
libvmaf/src/model.h
libvmaf/src/svm.cpp
libvmaf/src/svm.h
libvmaf/src/unpickle.cpp
libvmaf/src/unpickle.h
libvmaf/test/meson.build
libvmaf/test/test_model.c

Initial implementation of `VmafModel` as well as the unpickler for reading from the `.pkl` model files.  Holds everything `LibsvmNusvrTrainTestModel` and `BootstrapLibsvmNusvrTrainTestModel` do, but there's no reliance on ptools specific types, which allows us to make a distinction between model data and the model file format. I'm still holding out for #360.
```
(VmafModel) *m = {
path = 0x00000001004002a0 "../../model/vmaf_v0.6.1.pkl"
type = VMAF_MODEL_TYPE_SVM_NUSVR
feature = 0x0000000100401460
n_features = 6
score_clip = (enabled = true, min = 0, max = 100)
norm_type = VMAF_MODEL_NORMALIZATION_TYPE_LINEAR_RESCALE
score_transform = {
enabled = true
p0 = (enabled = true, value = 1.7067469200000001)
p1 = (enabled = true, value = 1.7264384399999999)
p2 = (enabled = true, value = …
```

libvmaf: implement VmafModel

---

.travis.yml

Add GCC-7,8,9 and Clang-10 compile tests along with keeping the python tests and add a ffmpeg compile test.
@kylophone, is vmaf targeting a minimum compiler version? I don't particularly see any mention of anything like that.
Questions:
- Should I add a macOS build job?
- Should I test if running vmaf through ffmpeg works?
- Should I remove the python2 tox job? https://pythonclock.org/
- Would you prefer these to be in Travis-CI or in Github Actions?
Anything else you think I should add?

Travis: Test multiple compilers and FFmpeg integration

---

libvmaf/src/predict.c
libvmaf/src/predict.h
libvmaf/test/meson.build
libvmaf/test/test_predict.c

Here is the initial implementation for `vmaf_predict_score_at_index()`. Given a `VmafModel` and a `VmafFeatureCollector` this function computes the vmaf score at a particular index. The value of `vmaf_score` is both returned in a pointer and also added to the `VmafFeatureCollector`. 
See `test_predict_score_at_index()` for usage.

libvmaf: implement vmaf_predict_score_at_index

---

libvmaf/src/vmaf.cpp
libvmaf/tools/main.cpp

Make JSON more coherent with XML (which already outputs pool).
Contrary to the XML output, JSON pool parameter will always be
exported.

Add --pool to print_usage()

---

python/script/ffmpeg2vmaf.py
python/script/run_cleaning_cache.py
python/script/run_psnr.py
python/script/run_result_assembly.py
python/script/run_testing.py
python/script/run_vmaf.py
python/script/run_vmaf_in_batch.py
python/script/run_vmaf_training.py
python/setup.py
resource/doc/VMAF_Python_library.md
third_party/libsvm/python/svm.py
third_party/libsvm/python/svmutil.py
third_party/libsvm/tools/checkdata.py
third_party/libsvm/tools/easy.py
third_party/libsvm/tools/grid.py
third_party/libsvm/tools/subset.py
unittest

This removes all references to python and instead uses python3, which is
to be used according to https://www.python.org/dev/peps/pep-0394/.
Particularly, distributors may choose not to provide python as a standalone
command.

update to python3

---

libvmaf/tools/meson.build

By default, both_libraries() returns the dynamic version.

Link vmafossexec with static version of libvmaf

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/meson.build
libvmaf/src/output.c
libvmaf/src/output.h
libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

Implements `vmaf_write_output()`, a `libvmaf` library function for writing an output stats file.

libvmaf: implement vmaf_write_output()

---

appveyor.yml

Since MSVC builds are still broken due to pthread dependencies, I've left the code to enable them, but commented them out.

Appveyor: Add mingw-w64 builds

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/integer_psnr.c
libvmaf/src/feature/integer_ssim.c

Updated callback signature for VmafFeatureExtractor `init()`. Also updated are feature extractors `float_ssim` and `float_psnr` to take advantage of the updated callback. Each feature extractor now only allocates its float buffers just once.

libvmaf: update VmafFeatureExtractor init

---

libvmaf/src/vmaf.cpp

This data was already in the xml, but not in the json.

Print aggregate data to json

---

libvmaf/src/vmaf.cpp

The vmafossexec is pretty noisy when --ci is used, and all the
printed information is available in the json or xml files.

Debug print model scores

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/motion.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/meson.build
libvmaf/src/output.c
libvmaf/test/meson.build
libvmaf/tools/cli_parse.c

Implements `float_motion` feature extractor, wrapping the existing float implementation.

libvmaf: implement vmaf_fex_float_motion

---

.travis.yml

Since `clang-10` doesn't seem to be an installable package any more, let's just use the most recent `clang` package.

travis: use most recent clang package

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/float_vif.c
libvmaf/src/feature/integer_psnr.c
libvmaf/src/feature/integer_ssim.c
libvmaf/src/libvmaf.rc.c
libvmaf/test/test_feature_extractor.c

Implements `vmaf_use_features_from_model()`. Function call used for registering all feature extractors required by a specific model.

libvmaf: implement vmaf_use_features_from_model

---

libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/float_vif.c
libvmaf/src/feature/picture_copy.c
libvmaf/src/feature/picture_copy.h

A few `libvmaf` feature extractors require an offset of -128, this PR implements that in `libvmaf_rc` for the wrapped `VmafFeatureExtractor`s.

libvmaf: add pixel offset for float feature extractors

---

libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/meson.build
libvmaf/tools/vidinput.c
libvmaf/tools/vidinput.h
libvmaf/tools/vmaf.c
libvmaf/tools/yuv_input.c

Addresses #441. Example usage is as follows:
```sh
./build/tools/vmaf_rc  \
--reference test422.yuv  \
--distorted test422.yuv \
--width 1920 \
--height 1080 \
--pixel_format 422 \
--bitdepth 8 \
--model ../model/vmaf_v0.6.1.pkl \
--output out.xml
```

vmaf_rc: add support for raw yuv

---

libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/float_vif.c

AVX2 requires aligned buffers.  Happened to work fine on some platforms, but only because of UB.

libvmaf/feature: use aligned_malloc for float buffers

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/ms_ssim.h
libvmaf/src/meson.build

Implements `ms_ssim` as a `VmafFeatureExtractor`, wrapping the original `compute_ms_ssim()` function.

libvmaf: implement vmaf_fex_float_ms_ssim

---

libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/float_vif.c
libvmaf/src/feature/picture_copy.c
libvmaf/src/feature/picture_copy.h
libvmaf/tools/vmaf.c
libvmaf/tools/yuv_input.c

This PR adds support for high bitdepth inputs.

libvmaf/vmaf_rc: add support for high bitdepth input

---

libvmaf/src/fex_ctx_vector.c
libvmaf/src/fex_ctx_vector.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/meson.build
libvmaf/src/thread_pool.c
libvmaf/src/thread_pool.h
libvmaf/test/meson.build
libvmaf/test/test_thread_pool.c

Implements the `VmafThreadPool` api, and also a second commit which opens the `fex_ctx_vector` api. One more commit is coming, which will tie these two things together and give frame parallelism and multithreaded feature extraction.

libvmaf: implement VmafThreadPool api

---

appveyor.yml
libvmaf/tools/meson.build

The uploading of artifacts to AppVeyor was removed in #384 with the change to the Meson build system. This PR re-enables the uploading of libvmaf and the vmaf tools to AppVeyor, as well as the Meson logs and a zip of the whole libvmaf/build directory.
@Elypha Does this satisfy your requirements? Or do you need anything else uploaded?
Closes #477.

AppVeyor: Re-add artifacts

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/test/test_feature_extractor.c

Implements a pool for pre-allocated `VmafFeatureExtractorContext` objects. When used with `VmafThreadPool` frame parallel feature extraction is possible.

libvmaf: implement vmaf_fex_ctx_pool

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/float_motion.c
libvmaf/src/libvmaf.rc.c
libvmaf/test/meson.build
libvmaf/test/test_feature_extractor.c

This adds a buffer flush API for feature extractors. Addresses #480.

Implement vmaf_feature_extractor_context_flush

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/libvmaf.rc.c

Implements multithreaded feature extraction in `libvmaf_rc`. Multithreading compares similarly to `vmafossexec` for now, but there is opportunity for more speed as each feature extractor is improved to reference `VmafPicture` pixel data directly. See the tables and graphs [here](https://docs.google.com/spreadsheets/d/1NZ-PZq9rbHLcB-R53lulxQCbaakc3B9T9wX_3Y5I2AU/edit#gid=0) for speed measurements.

libvmaf: add multithreading, feature extractor parallelization

---

libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
python/test/vmafrc_test.py

Fixes the regression introduced when 10-bit input was implemented. PSNR, SSIM, MS-SSIM feature extractors do not use a pixel value offset.

fix libvmaf_rc regression

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/libvmaf.rc.c
libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

This implements a CPU mask feature, which allows a user to restrict permitted CPU instruction sets. This is an incomplete solution, imho, since we currently only support x86 instruction sets. The fix for that will come later since it is indeed more involved, but for now the `vmafossexec` flag `--disable-avx` can be replicated in `vmaf_rc` with `--cpumask -1`.

libvmaf: implement cpumask

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/integer_psnr.c

This adds support for 10-bit PSNR, calculation is consistent with the `psnr_float` 10-bit feature extractor.

libvmaf: add support for hbd integer psnr

---

libvmaf/include/libvmaf/libvmaf.h

Regressed by 82a86e040371
```
$ hg clone https://bitbucket.org/multicoreware/x265/
$ cmake -GNinja -DENABLE_LIBVMAF=on x265/source
$ ninja
[...
ld: error: undefined symbol: compute_vmaf(double*, char*, int, int, int (*)(float*, float*, float*, int, void*), void*, char*, char*, char*, int, int, int, int, int, int, int, char*, int, int, int)
>>> referenced by api.cpp
>>>               api.cpp.o:(x265_calculate_vmafscore) in archive libx265.a
>>> referenced by api.cpp
>>>               api.cpp.o:(x265_calculate_vmaf_framelevelscore) in archive libx265.a
>>> did you mean: extern "C" compute_vmaf
>>> defined in: /usr/lib/libvmaf.so
```
```
$ git clone https://github.com/HomeOfVapourSynthEvolution/VapourSynth-VMAF
$ cd VapourSynth-VMAF
$ LDFLAGS=-Wl,-z,defs meson _build
$ ninja -C _build
ld: …
```

Restore extern "C" for C++ consumers

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/output.c
libvmaf/tools/cli_parse.c

Add support for JSON output.  Set `--json` from the `vmaf_rc` command line to use.

libvmaf: add support for JSON logging

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/output.c
libvmaf/tools/cli_parse.c

Adds support for csv logging to `libvmaf_rc`. Applies on top of #514.

libvmaf: add support for CSV logging

---

libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/output.c
libvmaf/src/output.h

Adds width, height, and fps stats to the XML output file.
```xml
<VMAF version="RELEASE_CANDIDATE">
<params width="576" height="324" />
<fyi fps="66.44" />
<frames>
<frame frameNum="0" motion2="0.000000" adm2="0.962171" adm_scale0="0.946342" adm_scale1="0.939103" adm_scale2="0.957538" adm_scale3="0.981014" vif_scale0="0.505393" vif_scale1="0.878155" vif_scale2="0.937589" vif_scale3="0.964358" ../model/vmaf_v0.6.1.pkl="83.868099" />
<frame frameNum="1" motion2="4.215693" adm2="0.949842" adm_scale0="0.929862" adm_scale1="0.916670" adm_scale2="0.938517" adm_scale3="0.978180" vif_scale0="0.411091" vif_scale1="0.811943" vif_scale2="0.894037" vif_scale3="0.937140" ../model/vmaf_v0.6.1.pkl="82.661630" />
<frame frameNum="2" motion2="4.070274" adm2="0.943535" adm_scale0="0.912681" …
```

libvmaf/output: add width, height, fps to xml log

---

Dockerfile
libvmaf/README.md
resource/doc/VMAF_Python_library.md

- Fix usage of executables: These can now be called without a `./` prefix.
- Fix installation of libvmaf

improve installation instructions

---

.github/workflows/libvmaf.yml

Replicates some of the jobs in travis-ci

Actions: Add libvmaf.yml

---

.github/workflows/ffmpeg.yml

Currently has macOS disabled because of errors with assembly with and without libvmaf and x86-asm
https://github.com/1480c1/vmaf/runs/623473257?check_suite_focus=true
Fixed macOS build thanks to @ePirat
https://github.com/1480c1/vmaf/actions/runs/89530778

Actions: Add an ffmpeg build

---

libvmaf/src/feature/feature_collector.c

Mutex should be unlocked before destruction. Otherwise, this may lead to undefined behaviour (see https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_mutex_destroy.html)

Mutex unlock before destroy

---

libvmaf/include/libvmaf/libvmaf.h

I struggled to make VMAF's C API work, so I have written down a few observations in comments to be parsed by Doxygen in `libvmaf.h`.
The comment I have written describes usage of `compute_vmaf`. It does not cover every parameter, but most importantly covers `read_frame`, whose exact requirements I found to be hopelessly ambiguous from the function signature alone.
This documentation could definitely use more work, but I believe having a basic description of the function and a few of its parameters will be of great value to new users.

Add some documentation to compute_vmaf in libvmaf.h

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/output.c
libvmaf/src/output.h
libvmaf/tools/cli_parse.c

This PR adds an additional output format for subtitles. These subtitles are in the [MicroDVD](https://en.wikipedia.org/wiki/MicroDVD) format which can be played back via `ffplay`, `mpv`, `vlc`, etc. I chose this format because it is frame accurate and requires no timing information (unlike srt). Usage with `vmaf_rc` is as follows:
```sh
--reference ./y4ms/ducks.y4m  \
--model path=../model/vmaf_v0.6.1.pkl \
--output output.sub \
--sub
```
Playback looks like this (pick one):
```
mpv y4ms/ducks_dist.y4m --sub-file output.sub
```
```
vlc y4ms/ducks_dist.y4m --sub-file output.sub
```
```
ffplay -vf subtitles=output.sub -i y4ms/ducks_dist.y4m 
```
Using the player of your choice, you may use the transport to step frame by frame and …

libvmaf, add subtitle output format

---

libvmaf/src/dict.c
libvmaf/src/dict.h
libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/integer_psnr.c
libvmaf/src/libvmaf.rc.c
libvmaf/src/meson.build
libvmaf/src/opt.c
libvmaf/src/opt.h
libvmaf/test/meson.build
libvmaf/test/test_dict.c
libvmaf/test/test_feature_extractor.c

Simple key/value dictionary. This dictionary will be used to implement filter initialization options. See `test/test_dict.c` for api usage examples.

libvmaf: VmafDictionary, VmafOption, parameterized feature extraction

---

libvmaf/include/libvmaf/feature.h
libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/dict.c
libvmaf/src/dict.h
libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/libvmaf.rc.c
libvmaf/test/test_dict.c
libvmaf/test/test_feature_extractor.c
libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

Updates the `vmaf_use_feature()` api call to take an options dict, which allows passing of feature options from the public api. This is a breaking change to the `libvmaf_rc` api, but this is still an unpublished release candidate api, so not an issue. 
If you'd like to specify feature options from the `vmaf_rc` command line, usage is as follows. key/value options are set with a `=` and each individual option is delimited with a `:`. This syntax should be familiar if you are used to `libavfilter` filter strings. 
```bash
./vmaf_rc --feature psnr=enable_chroma=false:second_param=123:third_param=1.414 ...`
```
Specifically setting options is not a requirement and thus can be omitted if not required. If a feature extractor has an available option and it is not set, the default value will be …

libvmaf feature options: public api, cli

---

libvmaf/tools/cli_parse.c
libvmaf/tools/meson.build

While `strsep()` is not as portable as `strtok()`, it is a much better alternative. This PR provides a compatibility shim, and should fix the Windows build.

vmaf_rc: provide a strsep compatibility shim

---

libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_ansnr.c
libvmaf/src/feature/float_moment.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/float_vif.c
libvmaf/src/feature/picture_copy.c
libvmaf/src/feature/picture_copy.h

`convolution_f32_avx_s` operates with the assumption that float buffer strides are always mod32, which means float buffers need to be padded whenever `((w * sizeof(float)) % 32) != 0`. I've gone ahead and padded all of them, even though not all of them call the convolution. This fixes a mismatch in `float_motion`.

feature/float_*: avx2 convolution assumes float buf stride is mod32

---

libvmaf/test/meson.build

This should fix #518 which affects building with meson versions before 0.50.0.

Fix test include directories in older meson versions

---

libvmaf/meson.build

libvmaf.pc version wasn't properly sync when we moved from 1.3.15 to 1.5.1.
Increase meson.project_version() to resync release and .pc file.
Signed-off-by: Alexandre Demers <alexandre.f.demers@gmail.com>

Update meson.build to next release version (1.5.2) to sync libvmaf.pc

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/libvmaf.rc.c
libvmaf/test/meson.build
libvmaf/test/test_context.c
libvmaf/tools/vmaf.c

This PR adds two API functions which brings the following functionality:
- Retrieve an individual feature score at a specific index.
- Retrieve a pooled score for a specific feature on a given interval.
`vmaf_feature_score_at_index()`
`vmaf_feature_score_pooled()`

libvmaf: add api functions to retrieve individual and pooled feature scores

---

libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h

To avoid shortopt clutter, remove shortopt support for most of the optional flags.

vmaf_rc: remove support for a few optional shortopts

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/libvmaf.rc.c
libvmaf/tools/vmaf.c

Replaces the use of `FILE *` with `const char *` in `vmaf_write_output()`. Solves #632.

libvmaf_write_output: avoid use of FILE type in public api

---

.github/workflows/ffmpeg.yml
.github/workflows/libvmaf.yml
.travis.yml
appveyor.yml
libvmaf/README.md
libvmaf/meson_options.txt
libvmaf/src/cpu.c
libvmaf/src/cpu.h
libvmaf/src/ext/x86/x86inc.asm
libvmaf/src/libvmaf.cpp
libvmaf/src/meson.build
libvmaf/src/x86/cpu.c
libvmaf/src/x86/cpu.h
libvmaf/src/x86/cpuid.asm
libvmaf/test/meson.build
libvmaf/test/test_cpu.c

This PR adds cross-platform CPU detection at both compile time as well as runtime. Should compile just fine on non-x86 platforms, and for x86 platforms adds an API for querying and masking CPU capabilities. This is easily extended to other platforms like ARM if we want to add some NEON in the future. This implementation borrows heavily from dav1d.
It should be noted that this adds an additional build dependency for x86, `nasm`. 
For example usage, see the following [test](https://github.com/Netflix/vmaf/compare/vmaf_init_cpu?expand=1#diff-3447e17508e4736b1d8768e040bfdb1eR32-R42). Capability querying and masking API is [here](https://github.com/Netflix/vmaf/pull/638/commits/50fb101eee495dff0d418c92ee61b6b8d12697aa#diff-fdc84b2396c69d94b2f41c05b90997c7).
Next steps: 
- Fix the old CPU …

libvmaf: Add cross-platform CPU detection

---

libvmaf/src/darray.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/integer_motion.c
libvmaf/src/fex_ctx_vector.c
libvmaf/tools/read_frame.c

Trying to build the latest version lead to a few errors about implicit function declaration, such as
```
../src/darray.c:26:2: error: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Werror,-Wimplicit-function-declaration]
```
Rather than try to work around it I tracked them down and added the missing includes which allows this to build cleanly for me.

add missing includes

---

libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

Adds an option (`--quiet/-q`) for manually disabling the realtime fps meter when run in a tty, useful for avoiding the overhead the fps meter brings when benchmarking. Also in this PR is a modification to how often FPS is computed. Instead of computing fps every frame, now fps is computed every 10 frames.

vmaf: add --quiet/-q option

---

libvmaf/include/libvmaf/feature.h

the return type was missing on `vmaf_feature_dictionary_set` causing compilation problems. This fixes it.

add missing return type to `vmaf_feature_dictionary_set`

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_ansnr.c
libvmaf/src/feature/float_moment.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/float_psnr.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/float_vif.c
libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/integer_motion.c
libvmaf/src/feature/integer_psnr.c
libvmaf/src/feature/integer_ssim.c
libvmaf/src/feature/integer_vif.c
libvmaf/src/libvmaf.rc.c
libvmaf/test/test_feature_extractor.c

This PR lays the groundwork for the feature extractors to receive 90-degree translated versions of the pics in the `.extract()` callback. Note that pics are not being passed yet, but the API now supports it. Creation and passing of pics will come in a future PR.

libvmaf/feature_extractor: update extract() callback to receive 90-degree translated pics

---

libvmaf/src/feature/adm_tools.c

SSE is not guaranteed to be present on x86 hosts, so i386..i686
compilers default to -mno-sse. That however makes the build fail
because vmaf unconditionally uses emmintrin functions which are
not available under no-sse. ppc64le builds however are just fine, so...
Change the macro guarding emmintrin to not match on x86-like
architectures, but to match on the enablement of SSE2. The macro
"__SSE2__" is the gcc name and is true whenever -msse2 is enabled
(explicitly or implicitly); clang should behave the same. I have not
tested this under other compilers such as Microsoft, though.
Fixes: #374

build: unbreak x86 builds

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/libvmaf.rc.c
libvmaf/src/output.c
libvmaf/src/output.h

This PR adds pooled metrics to the XML/JSON output. By default all metrics are logged with all available pooling methods. Schema examples are presented below:
```xml
<VMAF version="65aa63bb">
<params qualityWidth="1920" qualityHeight="1080" />
<fyi fps="6.50" />
<frames>
<frame frameNum="0" adm2="0.965322" adm_scale0="0.919776" adm_scale1="0.936752" adm_scale2="0.969591" adm_scale3="0.984926" motion2="0.000000" vif_scale0="0.491630" vif_scale1="0.912308" vif_scale2="0.955577" vif_scale3="0.974090" vmaf="86.119865" />
<frame frameNum="1" adm2="0.887379" adm_scale0="0.880019" adm_scale1="0.846873" adm_scale2="0.879327" adm_scale3="0.910632" motion2="4.728896" vif_scale0="0.321134" vif_scale1="0.583292" vif_scale2="0.664394" vif_scale3="0.741000" vmaf="52.280668" />
<frame frameNum="2" …
```

libvmaf: add pooled metrics to xml/json output

---

libvmaf/src/feature/integer_vif.c
libvmaf/src/feature/integer_vif.h
libvmaf/src/feature/x86/vif_avx2.c
libvmaf/src/feature/x86/vif_avx2.h
libvmaf/src/meson.build

This PR adds AVX2 optimizations to the integer VIF feature extractor, specifically the convolutions at all four scales. These optimizations are numerically accurate and give somewhere around a 325% speedup on this feature extractor.
```
OLD:
VMAF version cbee5eb8
500 frames ⠀⢐ 4.75 FPS
NEW:
VMAF version cbee5eb8
500 frames ⠀⢐ 15.52 FPS
```

feature/x86: provide avx2 optimizations for vif convolutions

---

libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/integer_adm.h
libvmaf/src/feature/x86/adm_avx2.c
libvmaf/src/feature/x86/adm_avx2.h
libvmaf/src/meson.build

This PR adds AVX2 optimizations to the integer ADM feature extractor. These optimizations are numerically accurate and give somewhere around a 140% speedup on this feature extractor. This PR applies on top of #691.
```
OLD:
VMAF version 7e4c8727
500 frames ⠀⢐ 27.10 FPS
NEW:
VMAF version 7e4c8727
500 frames ⠀⢐ 38.69 FPS
```

feature/x86: provide avx2 optimizations for adm

---

.github/workflows/windows.yml

Also changes the flags "used" for the 32-bit jobs, still disabled since the output is `93.656205` instead of `93.656203`

Actions/windows: use the new syntax for setting environment variables

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/psnr_hvs.c
libvmaf/src/meson.build

This PR adds a PSNR-HVS feature extractor. This implementation was ported directly from daala tools, including their 8x8 fdct. There are optimized versions of the daala fdct available which can be integrated in the future.
```
--reference ./y4ms/ducks.y4m \
--feature psnr_hvs --no_prediction \
--output psnr_hvs.xml
```
```xml
...
<frame frameNum="478" psnr_hvs_y="23.317749" psnr_hvs_cb="32.605974" psnr_hvs_cr="35.802807" psnr_hvs="25.291056" />
<frame frameNum="479" psnr_hvs_y="22.664448" psnr_hvs_cb="31.907056" psnr_hvs_cr="35.320327" psnr_hvs="24.639031" />
<frame frameNum="480" psnr_hvs_y="22.977649" psnr_hvs_cb="32.122412" psnr_hvs_cr="35.497199" psnr_hvs="24.946156" />
<frame frameNum="481" psnr_hvs_y="23.257011" …
```

libvmaf/feature: port PSNR-HVS implementation from daala tools

---

libvmaf/src/feature/float_motion.c
libvmaf/src/feature/integer_motion.c

This PR adds the `motion_force_zero` parameter to the integer motion feature extractor. Possible enhancement and probably a more flexible approach might be adding a parameter to force the motion score to any floating-point value. That may or may not be useful.
```
--reference ./y4ms/ducks.y4m \
--feature float_motion=motion_force_zero=true \
--feature motion=motion_force_zero=true \
--no_prediction \
--output motion.xml
```

libvmaf/motion: add motion_force_zero to integer motion fex

---

.github/workflows/windows.yml
libvmaf/meson_options.txt
libvmaf/src/meson.build
libvmaf/tools/meson.build

This PR uploads the vmaf_rc.exe artifact on each Windows CI build. There are people are asking for builds, this is an easy way to provide them.

ci/windows: also upload vmaf_rc artifact

---

libvmaf/tools/vmaf.c

When reading y4ms, the intermediate buffer is mod16 padded. This assert will fail whenever the input resolution is not mod16, so we'll just remove it.

vmaf/fetch_picture: remove assert, ycbcr is mod16 padded

---

libvmaf/src/feature/float_adm.c
libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/integer_adm.h
python/test/vmafrc_feature_extractor_test.py
python/vmaf/core/vmafrc_feature_extractor.py

This PR adds the vif_enhn_gain_limit parameter to the integer vif feature extractor.
```
--reference ./y4ms/ducks.y4m \
--feature float_adm=adm_enhn_gain_limit=1.0 \
--feature adm=adm_enhn_gain_limit=1.0 \
--no_prediction \
--output adm.xml
```

libvmaf/feature: add adm_enhn_gain_limit param to integer adm

---

libvmaf/src/feature/x86/vif_avx2.c

This PR fixes a mismatch seen in vif_avx2 for inputs with the following parameters:
- `--width 480 --height 270 --pixel_format 420 --bitdepth 10`
- `--width 576 --height 324 --pixel_format 422 --bitdepth 10`
- `--width 160 --height 90 --pixel_format 420 --bitdepth 8`

vif_avx2: fix a mismatch for certain inputs

---

libvmaf/src/feature/alias.c
libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/integer_motion.c
libvmaf/src/feature/integer_vif.c

This PR renames the feature names written by the integer vif/adm/motion feature extractors to match what is published in the new model files. Additionally, features written by the floating point feature extractors are now logged with the `float_` prefix and the integer versions of these features no longer have the `integer_` prefix.

libvmaf/feature: rename features according to float/integer model requirements

---

libvmaf/include/libvmaf/libvmaf.rc.h
libvmaf/src/compute_vmaf.c
libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/integer_motion.c
libvmaf/src/libvmaf.rc.c
libvmaf/tools/vmaf.c

This PR adds a buffer flush mechanism to `vmaf_read_pictures()`. When you're done reading pictures call this function again with both `ref` and `dist` set to NULL to flush all feature extractors. In this framework, there can be feature extractors with temporal dependencies. When input pictures are finished a feature extractor may still have its own internal buffer which still needs to be drained. Currently,`motion` is the only feature extractor with the `VMAF_FEATURE_EXTRACTOR_TEMPORAL` flag. This API usage of passing `NULL, NULL` to flush buffers is similar to most encoding libraries.
Previously there were a few functions designed to be called after the `vmaf_read_pictures()` loop:
- `vmaf_feature_score_pooled()`
- `vmaf_score_pooled()`
- `vmaf_score_pooled_model_collection()`
- …

vmaf_read_pictures: feature extractor flush update

---

.github/workflows/ffmpeg.yml
.github/workflows/libvmaf.yml

Remove the need for ACTIONS_ALLOW_UNSECURE_COMMANDS, checkout never needed it and setup-python v2 does not use set-env anymore.
Closes #715

Remove ALLOW_UNSECURE on CI

---

libvmaf/src/model.c

Avoids a zero length array when built-in models are disabled. Should fix: https://github.com/Netflix/vmaf/pull/724#discussion_r530079551

libvmaf: avoid zero length array when built-in models are disabled

---

libvmaf/src/feature/integer_motion.c
libvmaf/src/feature/integer_motion.h
libvmaf/src/feature/integer_vif.c
libvmaf/src/feature/x86/motion_avx2.c
libvmaf/src/feature/x86/motion_avx512.c
libvmaf/src/feature/x86/motion_avx512.h
libvmaf/src/feature/x86/vif_avx512.c
libvmaf/src/feature/x86/vif_avx512.h
libvmaf/src/meson.build
libvmaf/src/x86/cpu.c

This PR adds AVX-512 optimizations for the VIF and motion feature extractors. To build with AVX-512 you must supply the meson option `enable_avx512`, for example: `meson setup -Denable_avx512=true build`. To mask AVX-512 execution at runtime set `--cpumask 16` when calling `vmaf_rc`.

libvmaf/x86: add AVX-512 optimizations for vif and motion

---

libvmaf/tools/cli_parse.c

When calling `vmaf_rc` with no `--model` flag, instead of bailing, VMAF model v0.6.1 is now enabled by default. This only works if compiled with built-in models, otherwise the behavior is the same as the previous version, a model file path must be explicitly provided.

vmaf_rc: if no model is specified, enable v0.6.1 by default

---

libvmaf/src/feature/integer_vif.c

Mismatch was fixed by b82432d86b61833108dfa9afe0d863894749d911.

vif/x86: set avx2/avx512 filter1d_16 for 12-bit inputs

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/meson.build
libvmaf/test/test_feature_extractor.c
python/test/vmafrc_test.py

This PR deprecates the ported version of daala ssim in libvmaf. `float_ssim` has always been the primary ssim implementation, with daala ssim only being ported as an auxiliary implementation. This is being deprecated to avoid any confusion about which ssim feature extractor should be used.

libvmaf/feature: deprecate daala_ssim

---

libvmaf/src/feature/ciede.c
libvmaf/src/feature/feature_extractor.c
libvmaf/src/meson.build

This PR implements the CIEDE2000 color difference metric. Mostly complete, but WIP until color formats besides BT.709 are supported. Comments and questions welcome. Usage is as follows:
```
--reference ./y4ms/ducks.y4m \
--feature ciede \
--no_prediction
```

libvmaf/feature: initial import of ciede2000

---

resource/doc/ffmpeg.md

There is an extra ":" in the path of line 77.

Doc/ffmpeg.md: Fix about the path description under Windows

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/integer_psnr.c
libvmaf/src/meson.build
libvmaf/tools/cli_parse.c

This PR adds a `--aom_ctc` flag the `vmaf` tool, as well as one preset `proposed`. Usage is as follows. This flag will preload the correct vmaf model as well as all the auxiliary metrics as required by the AOM CTC. If this proposal is accepted in AOM, we would have versioned presets (i.e. `--aom_ctc v1.0`). Presets discourage errors and should hopefully avoid having to specify an extended set of arguments.
```sh
./build/tools/vmaf  \
--reference ./y4ms/test8.y4m \
--distorted ./y4ms/test8dist.y4m \
--aom_ctc proposed \
--output output.xml
```
Also in this PR is a commit which is laying the initial groundwork for the APSNR metric. This metric is unique in that it is not calculated per-frame and then pooled, it is calculated over all the pixels in the video. There needs to be some framework …

vmaf: add --aom_ctc flag and `proposed` preset

---

libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/src/feature/integer_psnr.c
libvmaf/src/output.c
libvmaf/test/test_feature_collector.c
libvmaf/test/test_feature_extractor.c

This PR adds an API for aggregate scores to the feature_collector API. An aggregate score is one that is calculated not on a per-frame basis but over the entire length of the video. The immediate use case for this is APSNR, but it could be useful for any sort of temporal pooling method which used pixel based features to determine picture weights (for example). The API for getting and setting is as follows:
```c
int vmaf_feature_collector_set_aggregate(VmafFeatureCollector *feature_collector,
char *feature_name, double score);
int vmaf_feature_collector_get_aggregate(VmafFeatureCollector *feature_collector,
char *feature_name, double *score);
```
Also in this PR is the aggregate metric APSNR which is written out when the option `enable_apsnr=true` is set. Finally, the last commit adds …

libvmaf/feature_collector: add aggregate_vector api

---

README.md
libvmaf/README.md
libvmaf/tools/README.md

This PR is a final documentation pass before the `libvmaf` v2.0.0.
- Avoids external references, written as if the `libvmaf` directory was its own self-contained tree.
- Since the library should be linkable via C++, FFI, etc. the "incorporate VMAF into your C code" sections have been modified to discuss the API in a general context.
- Avoid mentions of the `ffmpeg` filter from the `libvmaf` tree, discuss `libvmaf` only.

libvmaf: final documentation pass before v2.0.0 release

---

libvmaf/include/libvmaf/feature.h
libvmaf/include/libvmaf/libvmaf.h
libvmaf/include/libvmaf/model.h
libvmaf/meson.build
libvmaf/src/dict.c
libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/libvmaf.c
libvmaf/src/meson.build
libvmaf/src/opt.c
libvmaf/src/opt.h
libvmaf/src/predict.c
libvmaf/src/svm.cpp
libvmaf/test/test.c
libvmaf/tools/main.cpp
libvmaf/tools/read_frame.c
libvmaf/tools/vmaf.c

One last tweak before the release. Use `const char *` throughout the libvmaf API where appropriate. Also in this PR are some commits which clean up several compilation warnings in libvmaf.

libvmaf: use const char* in API, clean up compilation warnings

---

libvmaf/include/libvmaf/libvmaf.h

Updates `VmafConfiguration.cpumask` to use an explicitly sized type: `uint64_t`. Checks one of the final boxes for #591.

libvmaf: use uint64_t for cpumask

---

libvmaf/src/output.c

The vmaf_feature_name_alias is used as the key, this simplifies
the parsing code. For example, with the previous code, extracting
VMAF from the output file required something along the lines of
```
for m in vmaf_json["pooled_metrics"]:
if m["metric"] == "vmaf":
print("VMAF %f" % m["pooling_methods"]["mean"])
```
it can now be achieved as follows
`  print("VMAF %f" % vmaf_json["pooled_metrics"]["vmaf"]["mean"])`

output pooled_metrics as JSON object instead of array

---

libvmaf/src/feature/integer_adm.h

Fixes a buffer overread in `adm_avx2.c` (see below). 128-bit vectors were being loaded, which was longer than the allocated length of the filter. Filter arrays are zero padded now to accommodate the 128-bit AVX2 vector load. 
https://github.com/Netflix/vmaf/blob/7ec3811c0876ca88a687a6c958b3a4b874656f88/libvmaf/src/feature/x86/adm_avx2.c#L44-L50

libvmaf/integer_adm/avx2: fix asan issues

---

libvmaf/src/fex_ctx_vector.c
libvmaf/test/test_feature_extractor.c
libvmaf/test/test_model.c
libvmaf/tools/vmaf.c

Cleans up all memory in `libvmaf` tests which was previously not `free`'d. It's good to keep these leakless since it's just more lsan noise if we don't.

libvmaf/test: clean up all test allocations

---

libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/float_ssim.c
libvmaf/tools/cli_parse.c

This PR adds an `enable_db` parameter to both `float_ssim` and `float_ms_ssim` to enable reporting of the SSIM/MS-SSIM scores in dB. Default behavior of reporting linear scores does not change. Usage is as follows:
```sh
--feature float_ssim=enable_db=true
--feature float_ms_ssim=enable_db=true
```

ms_ssim/ssim: add enable_db parameter for reporting of scores in dB

---

libvmaf/include/libvmaf/libvmaf.h
libvmaf/src/compute_vmaf.c
libvmaf/src/libvmaf.c
libvmaf/src/log.c
libvmaf/src/log.h
libvmaf/src/meson.build
libvmaf/src/model.c
libvmaf/test/meson.build
libvmaf/test/test_log.c

Adds an internal logging api `vmaf_log()`, addresses #365.
Also, another commit to log model loading failures and mention pkl deprecation.

libvmaf: add vmaf_log()

---

libvmaf/src/feature/x86/vif_avx2.c

Avoids ub and squelches a `-Wunsequenced` warning.

libvmaf/vif_avx2: avoid -Wunsequenced ub

---

libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/x86/adm_avx2.c

- Cleans up some unused variables in the avx2 code
- Avoids UB, use explicitly unsigned types where warranted

ADM cleanup, Warnings && UB

---

libvmaf/src/feature/integer_adm.c

`adm_dwt2_8_avx2` shows a mismatch for inputs with non mod8 widths. Likely due to the multi-scale subsampling process. For now we will detect such cases and avoid enabling the AVX2 path, in the future we will see about a proper fix.

adm_dwt2_8_avx2: avoid mismatch when width is not mod8

---

libvmaf/meson.build
libvmaf/src/meson.build
libvmaf/src/model.c
libvmaf/test/meson.build
libvmaf/tools/meson.build

Use `library()` so the `--default-library`  flag will have an effect, fixes #557 and an issue in #613
also fixes #752

meson: use library() and fix external builds

---

libvmaf/src/meson.build
libvmaf/src/model.c

This PR adds the 4k models to the list of compiled-in models. Addresses #744.

libvmaf: add 4k models to list of built-in models

---

libvmaf/README.md
libvmaf/tools/README.md

The word "depreciated" was used instead of "deprecated". I have corrected this.

The wrong word was used. This has been corrected.

---

libvmaf/test/test_dict.c

The test/test_dict.c program is missing const qualifiers on variables
holding VmafDictionaryEntry pointers returned by vmaf_dictionary_get().
This patch silences -Wdiscarded-qualifiers warnings.

Silence warnings for missing const qualifier.

---

libvmaf/tools/vmaf.c

The scores will be available in the output file and are probably
unwanted in the standard output if the user specified --quiet

Do not display collection scores if quiet and output are set

---

.github/workflows/windows.yml
libvmaf/meson.build
libvmaf/src/feature/float_ms_ssim.c
libvmaf/src/feature/float_ssim.c
libvmaf/src/feature/integer_psnr.c
libvmaf/tools/cli_parse.c
resource/doc/aom_ctc.md

This PR adds the following feature extractor options:
* `psnr`: `min_sse`
* `float_ssim` : `clip_db`
*  `float_ms_ssim`: `clip_db`
Along with these feature extractor options, `--aom_ctc v1.0` has been updated to clip PSNR/SSIM dB values according to the AOM CTC. Rationale for this is to avoid infinite values in the case of lossless comparisons.
Also in this PR is a commit to avoid building FFmpeg in our Windows Github Actions build. There is something in the CI environment which has changed which is causing this to fail. Rather than debug this now, I'm just turning it off. We have a separate CI job to build FFmpeg on Ubuntu and that is still active and passing.

Update --aom_ctc v1.0 to clip infinite dB values.

---

python/vmaf/tools/misc.py

Windows does not support fork for python multiprocessing

Fix running python scripts on Windows

---

resource/doc/BuildForWindows.md

These guides can be used to build vmaf.exe on Windows using powershell.

Updated the outdated guide to build on windows

---

libvmaf/src/compute_vmaf.c
libvmaf/src/feature/alias.c

This PR updates the `compute_vmaf()` wrapper to use the default PSNR feature extractor. With the default PSNR being used, the library does not need to build with non-default options to enable PSNR computations via `compute_vmaf()`. Should address #787. Also, while this fix is straight forward and reasonable, a reminder that `compute_vmaf()` is considered a deprecated API.

libvmaf/compute_vmaf: use default psnr

---

python/vmaf/tools/misc.py

Using the pathlib module is a less manual way of doing things and eliminates the possibility of confusion for readers who are Windows users where directories are separated by backslashes instead of forward slashes.

Use pathlib module.

---

python/vmaf/config.py
python/vmaf/core/train_test_model.py
python/vmaf/script/convert_vmaf_model_to_vmaf_no_enhn_gain_model.py
python/vmaf/tools/decorator.py
python/vmaf/tools/misc.py

Adding `exist_ok=True` prevents a `FileExistsError` if the specified directory already exists, removing the need for `if not os.path.exists(<directory>):`.

Use exist_ok=True to remove unnecessary if-statements.

---

python/setup.py

I'm unable to build latest VMAF on OS X, using Python 3.9.0 from homebrew (although the same problem repro'd with 3.7.5), and another coworker had the exact same problem on another machine.
The error is `unable to find "numpy/arrayobject.h"` in Cython, even though numpy is correctly installed, and `numpy.get_include()` returns the correct path (where I verified the headers exist).
For some reason `include_dirs` in setup.py is not being passed down. After thinking I'm losing my mind I did some searching and I see that other projects are experiencing the same problem, see for example https://github.com/hmmlearn/hmmlearn/issues/43 and the various other issues linking to it.
So I used the same workaround, instead manually setting the include dirs on the ext_module, and that seems to work just …

include_dirs do not appear to be getting passed properly on OS X 

---

resource/doc/external_resource.md

The description of my command-line tool now gives the reader a better idea of what it can be used for (to compare CRF values or presets). Also, the ability to encode to AV1 was added this year.

Add extra info about one of the FFmpeg-based tools.

---

python/vmaf/core/executor.py
python/vmaf/tools/stats.py

`is not` with a literal now throws SyntaxWarning in Python 3.8 or newer. This replaces those usages with `!=`. Also the float formatting in the doctests of `ListStats` can result in failures due to slight differences. This replaces their usage with float formatting so we can specify the necessary precision.
Also the doc tests were split into 2, with the bottom part not actually running. I salvaged some of those tests by moving them to the doctest block above and removed the ones that I believe were intended to be disabled.

fix formatting in ListStats doctests, fix warning in Python 3.8+

---

5PL_v1.py
python/test/train_test_model_test.py
python/vmaf/core/niqe_train_test_model.py
python/vmaf/core/train_test_model.py
resource/feature_param/ssim.py
unittest

Several papers such as [1][2] have mentioned that the following five-parameter logistic function (5PL) from [3] provide a good fit for linearizing non-linear VQA scores such as SSIM
I wanted to make this an option for training single feature models such as only based on SSIM. Based on tests in NFLX_public dataset this does appear to linearize slightly better than the current sigmoid, improving PCC from 0.750 to 0.770. Remains to be seen how this works on other data sets, but it feels like a reasonable option to have for evaluation purposes.
[1] A. K. Venkataramanan, C. Wu, A. C. Bovik, I. Katsavounidis and Z. Shahid, "A Hitchhiker's Guide to Structural Similarity". Submitted to IEEE Access.
[2] S. Athar and Z. Wang, "A Comprehensive Performance Evaluation of Image Quality Assessment …

add five-parameter logistic function as a model option

---

resource/doc/VMAF_Python_library.md

on latest CentOS `yum` has also been replaced by `dnf`. Also at least on CentOS `ninja` is available as `ninja-build`.  `python-dev` is also called `python-devel` on CentOS. Also adding some text to clarify the use of virtualenv for those less familiar with the nuances of Python development tools.

clarify python installation instructions

---

resource/feature_param/vmaf_feature_v6.py

The default (0.6.1) model uses `motion2` instead of motion, and yet the latest feature param file for vmaf is v3 which uses `motion`.  This adds a `vmaf_feature_v6.py` model which uses the same features as the baseline model to make it easier to start with the correct baseline for subsequent model explorations.

add vmaf feature param which uses motion2 instead of motion

---

libvmaf/include/libvmaf/picture.h
libvmaf/src/picture.c

There are no guards to protect against passing a monochrome picture to any of the chroma supporting feature extractors. Reverting bbeddc02e5f171a10ff8cfdfb6d23e290f169366 until there is a fix for #863.

Revert "Add support for yuv400p VmafPicture type (#861)"

---

libvmaf/src/feature/ciede.c
libvmaf/test/meson.build
libvmaf/test/test_ciede.c

Moves a few math library calculations to double precision, platform mismatch should be below the logging precision now.

libvmaf/ciede: avoid cross-platform mismatches

---

libvmaf/include/libvmaf/feature.h
libvmaf/include/libvmaf/libvmaf.h
libvmaf/src/dict.c
libvmaf/test/test_dict.c

A `VmafFeatureDictionary` may need to be free'd using the public api in case of failed calls to `vmaf_feature_dictionary_set()`.
Addresses #873.

libvmaf: add vmaf_feature_dictionary_free()

---

resource/doc/VMAF_Python_library.md

Fix the Python installation guide to make it easier to copy-paste commands for each OS.

Add separate instructions for each operating system

---

.github/workflows/docker.yml
README.md

With #884 the failing docker image build was fixed. This PR adds a Github action to ensure the docker build is working in the future.
Additionally, the badge for the docker action and the ffmpeg action is added to the main README.

Add ci job to validate docker build

---

libvmaf/tools/y4m_input.c

Lately FFmpeg has been writing y4ms with additional color info in the header. When the old daala y4m parser encounters these files, it overwrites its own buffer and segfaults. This commit is just a quick fix, and simply increases the size of that static buffer.
Should address both #889/#825.

tools/y4m_input: increase header buffer size to accomodate certain y4m files.

---

libvmaf/src/meson.build

Fixes: #903
This patch fixes headers lookup included w/ libvmaf subfolder prefix:
#include <libvmaf/libvmaf.h>
Basically, libvmaf.h includes headers in this way as well.
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

build: add top include dir to .pc file

---

libvmaf/src/thread_pool.c

Fixes #893. 
There may still be work in the queue but n_working=0 before the vmaf_thread_pool_runner loop fetches another job in the queue.  When calling vmaf_thread_pool_wait (and not stopping), we will still want to drain the queue. So only exit the wait loop when n_working = 0 && head == nullptr

Fix a race condition in vmaf_thread_pool_wait.

---

libvmaf/tools/y4m_input.c

The daala y4m reader is patched to align with AOM handling of 420mpeg2:
https://aomedia.googlesource.com/aom/+/2656f676d3fcdef83d1155cd91b1bfb7f657b486

y4m_input: do not resample chroma for 420mpeg2 input

---

libvmaf/src/libvmaf.c
libvmaf/src/output.c
libvmaf/src/output.h

The XML output contains a field with the FPS:
```
<fyi fps="11.12" />
```
This PR adds this field to the JSON output, which didn't have it previously.
```
{
"version": "21ecc2a7",
"fps": 11.36,
"frames": [
{
...
}
]
}
```
Command to reproduce:
```
vmaf --pixel_format 420 --bitdepth 8 -d yuvs/HoC1__av1-yuv420p-ffmpeg__960_540__qp32_vmaf86.64_psnr41.49_kbps706.25_fps25_r.yuv -r yuvs/HoC1__av1-yuv420p-ffmpeg__960_540__qp32_vmaf86.64_psnr41.49_kbps706.25_fps25_r.yuv --width 960 --height 540 --output out.json --json --feature cambi
```
To test it, I tried parsing the output with the `json` module in Python, and it parsed correctly.

Add FPS field to JSON output

---

libvmaf/test/test_cambi.c

The function that we're testing is a 3x3 mode filter with mirroring for the edges and which should take the smaller element in case of a tie in frequency.
The unit test for this function was only checking for elements in the middle of the matrix, but elements on the edge and corners can be problematic due to the mirroring. 
The previous test case was this one:
| 0 | 0 | 0 | 0 | 0 |
|---|---|---|---|---|
| 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 1 | 1 | 0 |
| 0 | 0 | 1 | 1 | 1 |
| 0 | 0 | 0 | 0 | 0 |
Added the following test cases:
------------
Input:
| 2 | 1 | 0 | 0 | 0 |
|---|---|---|---|---|
| 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 1 | 1 | 0 |
| 0 | 0 | 1 | 1 | 1 |
| 0 | 0 | 0 | 0 | 0 |
Expected output:
| 2 | 0 | 0 | 0 | 0 |
|---|---|---|---|---|
| 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 0 | 1 | 0 |
| 0 | 0 | 0 | 1 …

Add test cases to CAMBI filter_mode unit test

---

libvmaf/src/feature/cambi.c
libvmaf/test/test_cambi.c

* Optimize `filter_mode` using a histogram to avoid quadratic time on each box
* Optimize `calculate_c_values` for better memory access patterns
* Optimize `get_spatial_mask_for_index` using DP square sums algorithm
* Eliminate need for `zero_derivative` image buffer by computing in-place
* Eliminate need for `filtered_image` buffer by filtering in-place
* Format `cambi.c` file for consistent style and spacing
* Add unit test cases on some functions
* Results:
* Speedup ranging between x1.6 (on low resolutions) and x4.5 (on 4k resolution)
* Memory usage down from 150MB to 125MB in 4k resolution
* CAMBI score remains unchanged (compared to `master`)

Optimize CAMBI code in libvmaf

---

libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/test/test_feature_collector.c

This PR adds a function for writing formatted feature names. See test for example usage.

libvmaf: add vmaf_feature_collector_append_formatted

---

libvmaf/src/feature/cambi.c
libvmaf/test/test_cambi.c

Instead of allocating and freeing memory on each call to `filter_mode`, allocate it once in `init` and free it in `close`. The results are identical on 10 benchmark videos, and the execution time is equal or very slightly faster. The main advantage is centralizing all memory allocations inside `init`.

CAMBI: Move mallocs to init to avoid allocating repeatedly

---

libvmaf/src/feature/cambi.c

When `n = k` in quick-select, we can immediately return as the top `n` elements will always be in the first `n` spots (the whole array). This fixes an edge case with this quick-select implementation which previously would have accessed out of bounds and caused UB. This case is never present in the actual CAMBI code with default parameters since `k = 0.6*n`, but could come up if the `topk` parameter is set to 1.

Fix quick-select for edge case n = k

---

libvmaf/src/feature/cambi.c
libvmaf/test/test_cambi.c
python/test/cambi_test.py
resource/doc/cambi.md

Add max_contrast parameter to account for larger contrast banding than 4 luma levels @ 10b  (e.g., for non-compression banding generated by bit-depth reduction).

Add max_contrast parameter

---

libvmaf/src/feature/feature_name.c
libvmaf/src/feature/feature_name.h
libvmaf/src/opt.h
libvmaf/test/test_feature.c

This PR adds a helper function for building parameterized feature names: `vmaf_feature_name_from_options()`. Parameterized feature names are constructed using a base feature name and a set of `VmafOptions` and a state struct.  Suffixes are added to the base feature name only when an option has a non-default value in the form of `_key_val`. The option name (`VmafOption.name`) is used for `key`, but an alias (`VmafOption.alias`) may also be used. This is a variadic function so feature names can be parametrized using any number of options. This is an allocating function, so normal usage inside a feature extractor would be to generate/allocate once in `.init()` and then free in `.close()`.
For example usage and output, see `test_feature_name_from_options()`.

libvmaf: add vmaf_feature_name_from_options

---

libvmaf/src/dict.c
libvmaf/src/dict.h
libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/src/feature/feature_name.c
libvmaf/src/feature/feature_name.h
libvmaf/src/feature/float_adm.c
libvmaf/src/feature/float_motion.c
libvmaf/src/feature/float_vif.c
libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/integer_motion.c
libvmaf/src/feature/integer_vif.c
libvmaf/src/fex_ctx_vector.c
libvmaf/src/opt.h
libvmaf/src/predict.c
libvmaf/test/meson.build
libvmaf/test/test_dict.c
libvmaf/test/test_feature.c
libvmaf/test/test_feature_collector.c
libvmaf/test/test_predict.c

This PR opens up feature name parameterization via one or several feature options. We previously supported something similar for a single key/val pair, but the new API supports many modifying options at once. Feature names are parameterized when a feature extractor `VmafOption` is set to a non-default and has its `VMAF_OPT_FLAG_FEATURE_PARAM ` flag set. Base feature names are extended with `_key_val` where `key` is `VmafOption.name` or `VmafOption.alias` if the alias exists. `val` comes from the non default value set when the feature extractor was registered. The parameter strings are appended in alphabetical order.
This PR also deprecates two previous attempts to provide similar functionality: `vmaf_feature_collector_append_templated()` and `vmaf_feature_collector_append_formatted()` …

libvmaf/feature: add vmaf_feature_collector_append_with_dict()

---

README.md

- (2021-12-1) We have added to CAMBI the `max_log_contrast` input parameter to allow to capture banding with higher contrasts than the default. We have also sped up CAMBI (e.g., around 4.5x for 4k).

Update on CAMBI changes

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/feature_name.c
libvmaf/src/feature/feature_name.h
libvmaf/src/fex_ctx_vector.c
libvmaf/src/predict.c

Small fix, prediction was failing when a feature extractor was overloaded with its default value.

libvmaf/predict: use vmaf_feature_name_from_options

---

libvmaf/tools/y4m_input.c

Earlier when we were trying to feed 422p10 files, vmaf did not support, with this patch it workss:) 
This is added based on how libaom handles of 422p10:
https://aomedia.googlesource.com/aom/+/28fe8d24fcd01cdaaf7e80ab6566df1f19ef6116/common/y4minput.c#1003

y4m_input: Add support for 422p10 y4m files

---

libvmaf/src/feature/x86/vif_avx512.c

Reproducible by running on a machine with avx512
```bash
curl -L "https://media.xiph.org/video/av2/y4m/AOV5_1920x1080_60_8bit_420.y4m" | ffmpeg -i - -s 458x214 -vframes 2 out.y4m
vmaf --reference out.y4m --distorted out.y4m --aom_ctc v1.0
```
clang on windows gives a warning of
```c
../libvmaf/src/feature/x86/vif_avx512.c:2025:47: warning: multiple unsequenced modifications to 'j' [-Wunsequenced]
for (unsigned j = n << 4; j < w; j = j++)
~  ^
```

vif_filter1d_rd_8_avx512: fix inf loop with j = j++

---

libvmaf/src/feature/cambi.c
libvmaf/src/feature/mkdirp.c
libvmaf/src/feature/mkdirp.h
libvmaf/src/meson.build
libvmaf/src/opt.c
libvmaf/src/opt.h

* Enables string options for VMAF
* Factors out buffers used by CAMBI from `CambiState`  into `CambiBuffers` to avoid clutter
* Adds optional parameter to CAMBI which provides a path to save one 16-bit YUV400 (grayscale) video for each scale, representing the `c_values` at that scale. This allows the user to visualize the bands detected by CAMBI and their temporal movement.
Comments:
* If we agree that the YUV400 option is better than the multiple PFM option, we can squash the last 4 commits into one. I'm keeping it this way for now in case we want to leave the last commit out (in which case, we can squash the last 3).
* It'd be good to test this on Windows, I don't have a Windows system but I'll try to find one to try it on. Mostly worried about the path separator.
* I've tested this on …

CAMBI heatmap generation

---

README.md
libvmaf/src/feature/cambi.c
libvmaf/test/test_cambi.c
python/test/cambi_test.py
python/vmaf/core/cambi_feature_extractor.py
python/vmaf/core/cambi_quality_runner.py
resource/doc/cambi.md

Added an optional flag `full_reference` to CAMBI to allow running it as a full-reference metric, subtracting the banding that is already present in the source and obtaining the "amount of banding added" by the encoding process. Added optional parameters `src_width`, `src_height` to allow different processing resolutions on source vs encode. 
Added a new feature extractor, `CambiFullReferenceFeatureExtractor`, to access this behavior from the Python interface.
Added a new quality runner, `CambiFullReferenceQualityRunner`, to wrap the feature extractor.
Added e2e tests and updated both `cambi.md` and the news section on `README.md`.
Some examples taken from the test AOM sequences where the full-reference CAMBI is significantly different from the no-reference CAMBI:
| Title  | No-Reference …

Full-reference mode for CAMBI

---

libvmaf/src/feature/cambi.c
libvmaf/src/feature/luminance_tools.c
libvmaf/src/feature/luminance_tools.h
libvmaf/src/meson.build
libvmaf/test/meson.build
libvmaf/test/test_cambi.c
libvmaf/test/test_luminance_tools.c

Since we want to use EOTFs outside of CAMBI, this PR factors out the EOTF functions into a separate file where they can be accessed by other features as well.

Factor EOTF out of CAMBI

---

libvmaf/src/feature/cambi.c
libvmaf/test/test_cambi.c
libvmaf/tools/cli_parse.c
resource/doc/cambi.md

CAMBI previously supported 8-bit and 10-bit inputs. This PR adds support for 12-bit and 16-bit inputs. Internally, CAMBI still works at the 10-bit level, and the inputs are upscaled/downscaled appropriately in the preprocessing steps.
Added unit tests to cover these cases, also manually upscaled a 10b video to 12b and 16b and the results were identical.
This PR refactors the upscaling/downscaling code into two functions, one to handle the case where the input is given as `uint8` and the other for `uint16`.

CAMBI: support 12-bit and 16-bit inputs by converting them to 10b

---

libvmaf/src/feature/cambi.c
libvmaf/src/feature/luminance_tools.c
libvmaf/src/feature/luminance_tools.h
libvmaf/test/meson.build
libvmaf/test/test_cambi.c
libvmaf/test/test_luminance_tools.c

Very simple change to have more explicit names.
`LIMITED` -> `VMAF_PIXEL_RANGE_LIMITED`
`FULL` -> `VMAF_PIXEL_RANGE_FULL`

More explicit names for enum types VMAF_PIXEL_RANGE_*

---

libvmaf/src/feature/cambi.c
libvmaf/src/feature/luminance_tools.c
libvmaf/src/feature/luminance_tools.h
libvmaf/test/test_luminance_tools.c

* Implement PQ EOTF and add a CLI option to use it in CAMBI for the visibility threshold calculations.
* Add a CLI option to CAMBI to provide the encoding bitdepth so it can choose whether to use the anti-dithering filter accordingly. This is for cases where the original bitdepth is < 10 and it has been upscaled to a bitdepth >= 10.
* A few minor style/uniformity changes.

Add flexibility to CAMBI CLI parameters

---

libvmaf/src/feature/cambi.c
libvmaf/test/test_cambi.c

These mutable global variables were causing issues when CAMBI was run multi-threaded, using the `--threads` CLI option for VMAF. Each thread would run malloc and free, and it resulted in freeing a non-malloc'd object and crashing. This PR eliminates those global variables and integrates them in `CambiState`. After this fix, running CAMBI with `--threads 8` doesn't crash anymore.

CAMBI: eliminate mutable global variables

---

libvmaf/src/feature/cambi.c

After the [full-reference](https://github.com/Netflix/vmaf/pull/968) CAMBI changes, the idea was to obtain `alloc_w` and `alloc_h` as the maximum of the encoding and source width and height (or just the encoding width if `full_ref == false`), and then use these variables to allocate enough space on the buffers. There were a few places where I didn't change `w` to `alloc_w` or `h` to `alloc_h`, potentially allocating too much space or too little space. This PR fixes this issue.

CAMBI: fix alloc_w, alloc_h bug

---

libvmaf/src/dict.c
libvmaf/test/test_dict.c

The `VMAF_DICT_NORMALIZE_NUMERICAL_VALUES` flag was causing string options like `123abc` to be chopped to `123`. This PR fixes this issue by only setting the flag if the input string is parseable as a float to begin with.

libvmaf: fix CLI parsing of string options that start with a number

---

libvmaf/src/feature/cambi.c

Remove the upper-resolution limit on which CAMBI can be computed. 
Looser lower-resolution limit: CAMBI can be computed on videos where width>=320 or height>=320.

CAMBI: remove the upper bound resolution and update the lower bound

---

.github/workflows/ffmpeg.yml

Currently the ffmpeg CI workflow is just failing silently on both [Ubuntu](https://github.com/Netflix/vmaf/runs/4984023460?check_suite_focus=true) and [Mac](https://github.com/Netflix/vmaf/runs/4984023520?check_suite_focus=true).
Ubuntu:
```
93.663925
vmaf Score doesn't match 93.656203
Error: Process completed with exit code 1.
```
Mac:
```
Run cat /proc/cpuinfo
cat: /proc/cpuinfo: No such file or directory
Error: Process completed with exit code 1.
```
This PR removes the line `cat /proc/cpuinfo` and updates the expected score so the test passes. If there is a reason to have the `cat` line, feel free to reject, but it doesn't seem to be doing anything.

Fix ffmpeg CI workflow

---

libvmaf/src/feature/vif_tools.c

This line was supposed to use `src2_stride`, but it uses `src1_stride`, likely due to a typo. `src2_stride` is then never used, which triggered a warning. Check line 561 where this stride is used to index `src2`.

Fix typo-related bug in `vif_tools.c`

---

libvmaf/src/feature/vif_tools.c
libvmaf/src/meson.build
libvmaf/test/meson.build

Meson is planning to change the default value of optional arguments in two functions:
* `run_command`: `check` will go from false to true, [link](https://github.com/mesonbuild/meson/issues/9300)
* `extract_all_objects`: `recursive` will go from false to true, [link](https://mesonbuild.com/Release-notes-for-0-46-0.html#recursively-extract-objects)
Since these don't affect our build, we can just add the keyword arguments to avoid warnings.

Fix meson warnings about missing keyword arguments

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/null.c
libvmaf/src/meson.build

Adds a very simple noop feature extractor. Useful for testing overall libvmaf throughput without any computational overhead which would be required from a real feature extractor.

libvmaf: add null feature extractor

---

libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

Adds a `--frame_cnt` cli option to `vmaf`. Mainly useful for performance testing with endless streams (`/dev/zero` et al.) or development/debugging with longer files. `vmaf` uses `--frame_cnt` as an upper bound maximum number of frames to process. Default behavior is unchanged.

libvmaf/vmaf: add --frame_cnt cli option

---

libvmaf/src/feature/adm.c

As mentioned in #1004, this function is used by a Cython file, but it's not used by any C code so it throws an "unused function" warning. My fix is to use `__attribute__((unused))`, which works on all compilers that I've tried. There are also a few usages of `__attribute__` in libvmaf already so I think it shouldn't restrict portability.
After this, the only warnings left are the deprecated `compute_vmaf` call and the `vif_avx2` file. There may be other warnings when compiling with `-Denable_avx512=true` which I haven't checked.

libvmaf: fix unused function warning in adm.c

---

libvmaf/src/feature/cambi.c
libvmaf/src/feature/x86/cambi_avx2.c
libvmaf/src/feature/x86/cambi_avx2.h
libvmaf/src/meson.build
libvmaf/test/test_cambi.c
python/test/cambi_test.py

- Simplification of `filter_mode` by separating it into iterated smaller mode filters
- Unrolling of loops in `calculate_c_values` so that edge case checking doesn't impact the majority of the loop iterations
- Default `window_size` changed from 63 to 65 for better computational performance
- SIMD implementation of the histogram updates
- Adjustment of the `mask_index` computation to fix small resolutions and not use floating point math
- Adjustment of the `window_size` computation to be rotation invariant and not use floating point math
- Update resolution limits to accept smaller and larger videos
These changes include #997, #999, #1000. Those PRs will be closed.

CAMBI: collection of changes that impact score

---

CHANGELOG.md
libvmaf/meson.build
libvmaf/tools/cli_parse.c
resource/doc/aom_ctc.md

This PR prepares the `--aom_ctc v3.0` preset. The only difference to previous versions is the addition of the `cambi` metric.

libvmaf/vmaf: prepare --aom_ctc v3.0 preset

---

python/test/executor_test.py
python/test/extra/ffmpeg_extratest.py
python/test/testutil.py
python/vmaf/core/executor.py

Currently, we're treating `workfile_yuv_type` like this:
* if both ref and dis are "notyuv", we use the type given by the user, or a default if not provided
* if one is "notyuv" and the other is some type of yuv, we use the type of the yuv, ignoring the user input
* if both are yuv, we assert that they're the same type and use that type, ignoring the user input
This PR makes it so that if the user inputs `workfile_yuv_type` in the asset dict, it overrides all other types and both the dis and ref files are converted to that type. It's achieved by modifying `_need_ffmpeg` and `_get_workfile_yuv_type ` from both `Executor` and `NorefExecutorMixin`.
This PR also adds two test cases, one for `FeatureExtractor` and one for `NorefFeatureExtractor`, which use this to override the yuv type from 8b …

If user provides workfile_yuv_type, override the assets' type

---

libvmaf/src/feature/integer_vif.c
libvmaf/src/feature/integer_vif.h
libvmaf/src/feature/x86/vif_avx2.c
libvmaf/src/feature/x86/vif_avx2.h
libvmaf/src/feature/x86/vif_avx512.c
libvmaf/src/feature/x86/vif_avx512.h
libvmaf/src/meson.build

This is a cleaned up, rebased and squashed version of #944. This performance bottleneck fix was identified and implemented by @foosoftsrl. Instead of a two-pass operation (filter, stats) now both operations have been pipelined and a costly second pass is not required. This is a significant contribution and the performance results speak for themselves. With AVX2 enabled, there is a **~16.6%** speedup over the master branch. The overall memory use is down by **~45%**. These gains come with no loss of numerical precision or inaccuracies. The following command was used to benchmark these changes. This is a 1920x1080 source with 130 frames. Thank you to @nilfm for the initial clean-up as well as very thoroughly testing the changes.
```
./build/tools/vmaf \
--reference …
```

libvmaf: pipelined vif feature computation

---

libvmaf/src/feature/integer_motion.c

Gives a ~10% memory reduction for 1080p vmaf. No speed changes.
before:
87638016  maximum resident set size
after:
79347712  maximum resident set size

libvmaf/motion: use single-channel buffers

---

README.md
resource/doc/features.md
resource/doc/index.md

"Metrics" is ambiguous. The term "features" should be consistently used.

rename metrics to features

---

libvmaf/src/feature/integer_adm.c

Addresses #1035, avoids a segfault at very low resolutions. Note that ADM probably doesn't make sense as a metric at these very small patch sizes.

integer_adm: add size check in init

---

libvmaf/src/feature/third_party/xiph/psnr_hvs.c

The xiph DCTs used in psnr_hvs were not designed for 16-bit input, and will overflow. This commit adds a check to fail for all bitdepths greater than 12. It may be possible to fix this with a different DCT, but in the meantime we will at least be guarded from bogus results. Partially addresses #1032.

libvmaf/psnr_hvs: add bitdepth check during init

---

libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

This command line option allows skipping the first N frame of the reference (source) when calculating VMAF, PSNR and other metrics. This is useful when only a clip of a source is coded and we need to calculate metrics only for the coded clip against the source. As --frame_cnt has been in the package, this PR is to address the case that the clip is not from the beginning of the source.

Add command line option --skip_ref_frame

---

libvmaf/src/feature/arm64/adm_neon.c
libvmaf/src/feature/arm64/adm_neon.h
libvmaf/src/feature/arm64/vif_neon.c
libvmaf/src/feature/arm64/vif_neon.h
libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/integer_vif.c
libvmaf/src/meson.build

The PR implements next 5 functions for the ARM64 architecture using intrinsics:
- subsample_rd_8()
- subsample_rd_16()
- vif_statistic_8()
- vif_statistic_16()
- dwt2_8()
Results are bit exact and speedup is x2 .

Adding ARM64 Neon implementation to the most demanding functions

---

libvmaf/README.md

As seen in https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages
The package name of ninja might be `ninja-build` or `ninja`, depending on the system.
I'd suggest changing to `ninja-build` as default but leave a note regarding the package name.

Change ninja package name and add warning note

---

resource/doc/vmafossexec.md

Since `libvmaf/build/tools` is generated at compile time, the link to it in the GitHub repository redirects nowhere.

Remove broken link to build output file

---

libvmaf/src/arm/cpu.c
libvmaf/src/arm/cpu.h
libvmaf/src/cpu.h
libvmaf/src/feature/integer_adm.c
libvmaf/src/feature/integer_vif.c
libvmaf/src/meson.build

This PR adds the ability to mask arm64 NEON optimizations at runtime. This is something that we already have for x86, and it is useful for debugging/benchmarking. This feature can be tested with the following command-line:
```sh
./build/tools/vmaf \
--reference ducks_take_off_1080p50.y4m \
--distorted ducks_take_off_1080p50.y4m.264.y4m \
--cpumask -1
```
fyi @RonenGvili

libvmaf/cpu: add vmaf_get_cpu_flags_arm

---

libvmaf/test/meson.build
libvmaf/test/test_model.c

Fixes testing out of tree (i.e.: when builddir is not subdir of libvmaf dir) by defining the path to the model dir contained in vmaf project relative to meson.project_source_root.

test_model: fix out of tree testing

---

libvmaf/tools/vmaf.c

During the process of developing and testing another feature extractor we encountered a memory leak in valgrind in cases where two inputs have unequal number of frames.
Co-authored-by: RakshithGB <luckydudefeelinggreat@gmail.com>

fix memory leak by freeing frame when one stream ends before the other

---

libvmaf/include/libvmaf/vmaf_cuda.h
libvmaf/include/libvmaf/vmaf_cuda_state.h
libvmaf/src/cuda/common.c
libvmaf/src/cuda/picture_cuda.c
libvmaf/src/feature/integer_adm_cuda.c
libvmaf/src/feature/integer_motion_cuda.c
libvmaf/src/feature/integer_vif_cuda.h
libvmaf/src/libvmaf.c
libvmaf/src/picture.h
libvmaf/test/test_ring_buffer.c

Two small updates:
- 3597d3665b473955979c8026ac3867fdf68eb341 avoids an unnecessary HAVE_CUDA macro
-   292598df547ed9e7a947e70767b497bac7f9a9b0 moves VmafCudaState to a separate header, this makes it possible to use cuda features without the inclusion of the `<cuda.h>` header, which complicates integration in some applications.

CUDA api updates, introduce vmaf_cuda_state.h

---

python/vmaf/routine.py

This PR allows caller to parse optional_dict when using run_test_on_dataset to run a metric on a dataset

Make it possible to parse optional_dict to run_test_on_dataset

---

libvmaf/src/feature/integer_psnr.c

Fix for issue found by @avstrakhov in #1115.

libvmaf/psnr: fix inaccuracy for some 16-bit measurements

---

libvmaf/src/feature/integer_vif.c
libvmaf/src/feature/x86/vif_avx512.c

Context: there was a numerical discrepancy in the AVX-512 implementation of VIF that led us to temporarily disable it. This PR fixes it and re-enables AVX-512 for VIF.

fix vif_avx512 bug; enable avx512 for vif

---

libvmaf/src/output.c

Addressing #1114 by outputting `null` in the cases where the FPS is infinity (because of clock precision). This is consistent with how we treat similar cases such as [here](https://github.com/Netflix/vmaf/blob/b34b8f01ff97c42620905cfb56432a8f51b33b74/libvmaf/src/output.c#L175). This way we no longer output invalid JSON.

fix inf fps error

---

libvmaf/src/libvmaf.c
libvmaf/src/output.c
libvmaf/src/output.h

Issue #1084 comes from a bug where the parameters passed to `vmaf_feature_score_pooled` are wrong in the case where subsampling is applied. This PR passes in the correct index.

Fix issue #1084

---

libvmaf/src/feature/integer_vif.c
libvmaf/src/feature/x86/vif_avx512.h

We were using an avx2 function in the avx512 version, pretty sure this was due to a typo in the original pipelining PR. I have tested on some inputs and results are identical. I haven't seen a significant speedup.

integer_vif: fix avx512 function usage

---

libvmaf/src/feature/cuda/integer_adm_cuda.c

This fixes issue #1155 
Wrong pointer was passed to the GPU causing a crash in a ADM_DWT kernel for 16 bits.

fixed device pointer argument

---

libvmaf/meson.build

On BSD operating systems (I tested FreeBSD and NetBSD), with _POSIX_C_SOURCE=200112L, M_PI (needed by src/feature/ciede.c) is not exposed.
_XOPEN_SOURCE=600 exposes a superset of _POSIX_C_SOURCE=200112L, including M_PI.
<details><summary>Description of attempt #1</summary>
On BSD operating systems (I tested FreeBSD and NetBSD), this has the effect of hiding M_PI, which is needed by src/feature/ciede.c.
A patch doing exactly this is [used in FreeBSD Ports](https://cgit.freebsd.org/ports/tree/multimedia/vmaf/files/patch-meson.build?id=6c807939df684267f5eaac09b70821de4f124b52).
</details>

libvmaf: use _XOPEN_SOURCE, not _POSIX_C_SOURCE 

---

libvmaf/src/feature/cuda/integer_adm_cuda.c
libvmaf/src/feature/cuda/integer_motion_cuda.c
libvmaf/src/feature/cuda/integer_vif_cuda.c

I found that when running with the "neg" model the feature names are not correctly propagated due to having different options on CUDA and normal feature extractors. 
```bash
$ vmaf -r data/distorted_1080p_yuv420p.yuv -d data/reference_1080p_yuv420p.yuv -w 1080 -h 1920 -p 420 -b 8 -m path=./model/vmaf_v0.6.1neg.json --gpumask 0 
VMAF version b9150a23
128 frames ⠋⠉ 273.88 FPS
libvmaf ERROR vmaf_predict_score_at_index(): no feature 'integer_adm2_egl_1' at index 0
problem generating pooled VMAF score
```
This PR fixes that but i am not sure if it would be more optimal to move the options for adm into `integer_adm.h` and "template" them with `AdmState` and `AdmStateCuda` due to different offsets. Currently it looks like a dangerous code duplication of the option definition.
@kylophone What do …

Fix: Missing alias on cuda options

---

libvmaf/src/fex_ctx_vector.c
libvmaf/src/fex_ctx_vector.h
libvmaf/src/libvmaf.c

Fix for #1167.
**Before**: `frame=  500 fps=215 q=-0.0 Lsize=N/A time=00:00:09.98 bitrate=N/A speed= 4.3x`
**After**: `frame=  500 fps=313 q=-0.0 Lsize=N/A time=00:00:09.98 bitrate=N/A speed=6.25x`

libvmaf/cuda: avoid unneeded device to host copy

---

python/test/asset_test.py
python/test/cambi_test.py
python/test/testutil.py
python/vmaf/core/asset.py
python/vmaf/core/cambi_feature_extractor.py
python/vmaf/routine.py
python/vmaf/tools/misc.py

This PR fixes a problem in ``CambiFeatureExtractor`` for cases where the encode's bitdepth is lower than the workfile's bitdepth. The previous version did not propagate ``enc_bitdepth`` to the executable which caused CAMBI not to compensate for the conversions from the original format to the workfile format (similarly as it compensates for scaling via ``enc_width`` and ``enc_height``). This led to lowering the CAMBI scores for 8bit videos with 10bit references when calculated via VMAF Python Library.
The PR consists of:
- adding ``dis_encode_bitdepth`` as a property of ``Asset``. The logic is to automatically assign this property for supported yuv files and return None for notyuv when not specified.
- adding the requirement for ``dis_encode_bitdepth`` to be specified (similarly to …

add dis_enc_bitdepth to CambiFeatureExtractor

---

libvmaf/src/feature/integer_vif.c

Hi
While doing release testing for  Bridgetech probes we found a memory leak when deinitializing the vmaf feature extractor. This can be verified in valgrind by initializing a vmaf scorer, scoring an image and cleaning up. Valgrind will then report that some memory is leaked. 
This PR contains a fix that fixes the leakage for us.  It seems like a free function call was lost during an earlier merge, so this PR adds the free back, so the code looks similar to the other feature extractors.

Fix memory leak: Free data when cleaning up feature extractor

---

python/vmaf/__init__.py

Merge in MCE/vmaf-private-lts from VCQ-101-refactor-to-enable-process-captor to master
Squashed commit of the following:
commit 4016747cf65291377b0175eca490084b8663fc80
Author: Zhi Li <zli@netflix.com>
Date:   Sun Jul 23 22:02:33 2023 -0700
VCQ-101 fix test.
commit 007fd77a01dfce92a914da69ddb8434e34193a89
Author: Zhi Li <zli@netflix.com>
Date:   Sun Jul 23 21:40:42 2023 -0700
VCQ-101 remove unused setUp and tearDown.
commit 500468efd439cf91c3c2a40d2f2b333c1dd7538c
Author: Zhi Li <zli@netflix.com>
Date:   Sun Jul 23 21:39:15 2023 -0700
VCQ-101 remove regular test_run_psnr_fextractor_5frms.
commit 2492f9ddff0786cef3ecd72cdcaf4114247f277b
Author: Zhi Li <zli@netflix.com>
Date:   Sun Jul 23 21:35:37 2023 -0700
VCQ-101 add tests of specific commands in the first command test.
commit …

Pull request #275: VCQ-101 refactor to enable process captor

---

libvmaf/src/feature/cuda/integer_adm/adm_cm.cu
libvmaf/src/feature/cuda/integer_adm/adm_dwt2.cu
libvmaf/src/feature/cuda/integer_adm_cuda.c
libvmaf/src/feature/cuda/integer_vif/filter1d.cu
libvmaf/src/feature/cuda/integer_vif_cuda.c

Superseding #1195
Text from 1195:
> Greatly lowers score difference on CUDA for high bit images.
> 
> VMAF score for 1000 frames of a 4096x2160 10bpc sequence in FFMPEG:
> with libvmaf_cuda (GPU):
> [Parsed_libvmaf_cuda_0 @ 0x559ffac22b00] VMAF score: 76.101209
> 
> with libvmaf (CPU):
> [Parsed_libvmaf_2 @ 0x55a7e344cf80] VMAF score: 76.101269
> 
> Score difference is now dependet on the sequence used.

Partially fix score difference for CUDA (bpc >=10) 

---

libvmaf/src/feature/x86/motion_avx2.c
libvmaf/src/feature/x86/motion_avx512.c
libvmaf/src/feature/x86/vif_avx2.c
libvmaf/src/feature/x86/vif_avx512.c

In cases where the input width is not a multiple of 16, there are issues with the AVX-2 and AVX-512 implementations of VIF, leading to small numerical discrepancies or even a segmentation fault. This PR addresses these issues.

Fix edge cases with AVX implementations of vif

---

libvmaf/tools/vmaf.c

Fix Y4M parsing

---

libvmaf/src/feature/arm64/vif_neon.c

The variable `i_dst_stride` is being updated inside the main loop. See lines 258 and 403. The way it's being used in the "scalar code for horizontal leftover" loop is incorrect - it should not be multiplied by `i`.
This bug affects neon code on widths not divisible by 32.
Addresses #1181

Fix vif_neon segmentation fault

---

libvmaf/src/feature/common/convolution_avx.c

Tested on GCC, and I don't get the warning from clang in the first place.

Fix fallthrough warnings

---

libvmaf/doc/meson.build

https://mesonbuild.com/Release-notes-for-0-56-0.html#mesonbuild_root-and-mesonsource_root-are-deprecated

Fix meson warning for deprecated source_root()

---

libvmaf/tools/cli_parse.c

In preparation for supporting aom_ctc v6.0, adding support for v4 and v5, which are identical to v3.

Add aom_ctc v4.0 and v5.0 CLI options

---

libvmaf/tools/cli_parse.c
libvmaf/tools/cli_parse.h
libvmaf/tools/vmaf.c

Continuation of #1260, with two extra commits to gate the behavior behind the new `--convert_bitdepth` CLI flag, and to add `--aom_ctc v6.0` enabling this flag.

tools/vmaf: support y4m input files with different bit depths; add command-line flag to gate this behavior

---

Dockerfile.cuda
libvmaf/README.md
resource/doc/docker.md

Actually the base image is a bit overkill. CUDA Toolkit is only required for compilation but not for execution. It should be sufficient to compile in a CUDA docker but copy everything over to the respective Ubuntu base image. Any help with reducing the image into a build image and a final image would be much appreciated ! If image size is not a concern this is working as is.

Docker + CUDA documentation

---

libvmaf/README.md

Removes the following warning
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```

Update meson command

---

libvmaf/src/svm.cpp

removes the following warning
```
../src/svm.cpp:57:2: warning: 'vsprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use vsnprintf(3) instead. [-Wdeprecated-declarations]
```

remove deprecation warning in svm.cpp

---

libvmaf/src/feature/picture_copy.c

'ISO C forbids ‘return’ with expression, in function returning void'

picture_copy: fix warning

---

python/vmaf/core/niqe_train_test_model.py

Newer numpy versions no longer allow passing in iterable objects to array stack. 
```
arrays to stack must be passed as a "sequence" type such as list or tuple
```
This has been a future warning for a while and I guess at some point it was actually removed. The easy fix is to wrap the map object in a list() call.

materialize map object before calling np.vstack

---

resource/doc/python.md

As reported in #1313 trying to install Python libraries on modern macOS will fail because Apple has explicitly disabled OpenMP support in clang. Instead mention installing and using the llvm from homebrew for the pip install.

update pip install instructions for macOS to use homebrew llvm

---

python/requirements.txt

Trying to install the Python requirements with a modern (3.11+) version of Python fails due to some internal API changes. See #1313 for more details
```
pywt/_extensions/_pywt.c:253:12: fatal error: 'longintrepr.h' file not found
```
it looks like even 3.10 does not build 
```
pywt/_extensions/_pywt.c:32259:5: error: expression is not assignable
++Py_REFCNT(o);
```
After doing some digging I'm not seeing a clear reason why PyWavelets was pinned to 1.1.1 in the first place. Unpinning it allows the requirements to install the wavelet related tests are passing. 
Some tests do fail with modern numpy versions due to some API changes, but those are unrelated and I'll address those in a separate PR.

unpin PyWavelets since 1.1.1 will not build with recent Python versions

---

libvmaf/src/model.c

I don't think this changes anything, since the size parameter `name_sz` was already computed from the lengths of the respective sources using `strlen`. This fixes the following warning:
```
warning: ‘__builtin_strncpy’ specified bound depends on the length of the source argument [-Wstringop-truncation]
```
Addresses #1228.

model.c: change strncpy to strcpy, fix warning -Wstringop-truncation

---

libvmaf/src/model.c

Partly addresses #1228. The mismatch is between these `extern` variables and the output of `xxd` which hex-dumps the model JSON files into unsigned char arrays in C files.

model.c: fix -Wlto-type-mismatch

---

.dockerignore
Dockerfile.cuda

fix: Dockerfile CUDA

---

libvmaf/src/feature/feature_extractor.c
libvmaf/src/feature/feature_extractor.h
libvmaf/src/feature/float_adm.c
libvmaf/src/framesync.c
libvmaf/src/framesync.h
libvmaf/src/libvmaf.c
libvmaf/src/meson.build
libvmaf/test/meson.build
libvmaf/test/test_framesync.c

Framesync API

---

.github/workflows/libvmaf.yml

Should fix #1278 and unblock #1292

github/workflows/libvmaf.yml: upload to a specific name for each matrix.oss and matrix.cc

---

python/vmaf/core/adm_dwt2_cy.pyx

Fixes the following warnings:
```
/home/coder/vmaf/.venv/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
17 | #warning "Using deprecated NumPy API, disable it with " \
|  ^~~~~~~
In file included from vmaf/core/adm_dwt2_cy.c:1221:
vmaf/core/../../../libvmaf/src/mem.c:19: warning: "_POSIX_C_SOURCE" redefined
19 | #define _POSIX_C_SOURCE 200112L
| 
In file included from /usr/include/x86_64-linux-gnu/bits/libc-header-start.h:33,
from /usr/include/limits.h:26,
from /usr/lib/gcc/x86_64-linux-gnu/11/include/limits.h:203,
from /usr/lib/gcc/x86_64-linux-gnu/11/include/syslimits.h:7,
from …
```

adm_dwt2_cy.pyx: fix cython warnings

---

.github/workflows/libvmaf.yml
.github/workflows/windows.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

.github: replace set-output with non-deprecated alternative

---

Dockerfile
Makefile

This seems like a more streamlined user experience to make sure they have the pip dependencies installed when they run `make` or `make install`.

Install python build dependencies in Makefile; simplify Dockerfile

---

Dockerfile

`xxd` is good to include because otherwise the built-in models are not compiled in

Dockerfile: simplify further, change entrypoint to vmaf CLI

---

python/vmaf/__init__.py

Regarding #1309, this brings both versions up to parity again but doesn't address the long term mismatch. Leaving that issue open until that is solved.

python/__init__.py: update python version to 3.0.0

---

libvmaf/src/feature/cambi.c

Replaces #1352. Benchmarks on my laptop show no observable overhead wrt master but need to check further.
(my benchmarks were on a 10-bit input so it's not just because of the early return in 8-bit and 16-bit cases)

cambi.c: validate input value ranges

---

python/test/asset_test.py
python/test/routine_test.py
python/vmaf/tools/sigproc.py

Currently we mute the warnings in tox.ini, this is a first step towards cleaning them up.

Fix warnings raised by pytest

---

libvmaf/test/meson.build

msys2's clang64 environment errors out due to undefined symbols with pthread.
The non-clang environments are fine as gcc implicitly links pthread.
Fixes https://github.com/Netflix/vmaf/issues/1362

test_feature_extractor: add thread_lib dependency

---

libvmaf/src/read_json_model.c

During the implementation of FUNQUE+ feature extractors we ran into the 32 max limit for JSON features and hand to bump this up to 64. In practice this may not be needed as not all exposed features are likely to be used, but we needed this to exhaustively exercise the feature extractor.
Co-authored-by: Mallikarjun Kamble <mallikarjun.kamble@ittiam.com>

increase max feature count to 64

---

libvmaf/src/output.c
libvmaf/src/output.h

During the implementation of FUNQUE+ feature extractors we ran into problems with ST-RRED due to the amount of leading zeros required. Even after applying some normalization factors it would still routinely exceed the 0.6f formatting in VMAF. However changing the default feature format to allow more zeros seemed invasive and broke a bunch of tests.
As a result we selectively enabled printing more digits only when required by the actual feature value, while maintaining compatibility with existing feature extractors which don't need this. 
This can wait until the FUNQUE+ feature extractor that requires it.
Co-authored-by: Priyanka-885 <priyanka.mane@ittiam.com>

Selectively allow more leading zeros when outputting feature values

---

python/vmaf/core/executor.py
python/vmaf/tools/misc.py

Improves the performance of the process pool by replacing the polling-based approach with Python's built-in process pool executor, which reduces synchronization overhead and reuses the Python interpreter when possible instead of spinning up a new instance for every single task.

Faster process pool

---

.travis.yml

These builds are currently broken.

.travis.yml: update to jammy

---

python/vmaf/core/cross_validation.py
python/vmaf/core/raw_extractor.py
python/vmaf/tools/misc.py
python/vmaf/tools/scanf.py

We already [specify](https://github.com/Netflix/vmaf/blob/master/resource/doc/python.md) that python should be >= 3.6, and use python3.6 features such as f-strings throughout the code base. This should make no difference to any users.

Clean up: remove support for python2

---

python/requirements.txt

Some of our python code is broken by the numpy v2.0.0 changes. Namely, printing numpy float values is now different:
* in numpy 1.x:
```
>>> a = {"a": np.float64(3.2)}
>>> print(a)
{'a': 3.2}
```
* in numpy 2.x:
```
>>> a = {"a": np.float64(3.2)}
>>> print(a)
{'a': np.float64(3.2)}
```
This doesn't play well with the `ast.literal_eval`-based parsing that we use. Longer term, we should get rid of `ast.literal_eval` and use JSON.

requirements.txt: pin numpy to <2.0.0

---

libvmaf/tools/cli_parse.c

This seems to be a copy and paste bug.
Calling "vmaf" with only -r option prints "could not open file: (null)". Instead it should print the correct usage hint.

[bugfix] Print required options hint for vmaf tool correctly

---

Dockerfile.cuda

Adjust the order and format of inputs to libvmaf_cuda  according to https://ffmpeg.org/ffmpeg-filters.html#toc-libvmaf_005fcuda
The libvmaf_cuda filter allows only `AV_FIX_FMT_CUDA` but `NV12`(sw_format) is not supported.
> https://github.com/FFmpeg/FFmpeg/blob/master/libavfilter/vf_libvmaf.c#L821C26-L821C41
So the current config raises `[libvmaf @ 0x7f95d00050c0] Unsupported input format: nv12` like below.
```
Stream mapping:
Stream #0:0 (h264) -> libvmaf_cuda
Stream #1:0 (h264) -> libvmaf_cuda
libvmaf_cuda:default -> Stream #0:0 (wrapped_avframe)
Press [q] to stop, [?] for help
[libvmaf @ 0x7f95d00050c0] Unsupported input format: nv12
[Parsed_libvmaf_cuda_0 @ 0x7f95d0004fc0] Failed to configure output pad on Parsed_libvmaf_cuda_0
[fc#0 @ 0x55b0b17da800] Error reinitializing filters! …
```

fix wrong ENTRYPOINT in Dockerfile.cuda

---

python/requirements.txt

The build has started failing with this error: 
```
TypeError: <lambda>() got an unexpected keyword argument 'nopython'
```
This is coming from the libsvm module. Past builds have succeeded with 3.32. Trying to pin to see if the upgrade to 3.33 has caused the failures.

Fix build by pinning libsvm-official to <=3.32

---

Dockerfile.cuda

```
An ARG declared before a FROM is outside of a build stage, so it can't be used in any instruction after a FROM
```
From https://docs.docker.com/reference/dockerfile/#understand-how-arg-and-from-interact

Fix ARG placement in Dockerfile.cuda

---

libvmaf/include/libvmaf/libvmaf.h
libvmaf/src/feature/feature_collector.c
libvmaf/src/feature/feature_collector.h
libvmaf/src/libvmaf.c
libvmaf/src/meson.build
libvmaf/src/metadata_handler.c
libvmaf/src/metadata_handler.h
libvmaf/src/predict.c
libvmaf/src/predict.h
libvmaf/test/meson.build
libvmaf/test/test_feature_collector.c
libvmaf/test/test_predict.c
libvmaf/test/test_propagate_metadata.c

Part of the [GSoC 2024](https://summerofcode.withgoogle.com/programs/2024/projects/yma73MGc) project.
Supports propagating metadata with modified `feature_vector_append`.

GSoC 2024: libvmaf: Propagate metadata

---

libvmaf/test/test_framesync.c

mingw provides a windows.h header, not Windows.h.  This causes a build failure when cross compiling from a Unix system with a case sensitive filesystem.

libvmaf: fix case of windows.h

---

libvmaf/meson.build

This used to set _POSIX_C_SOURCE.  [I tried to remove it](https://github.com/Netflix/vmaf/pull/1162), because it caused some functions to be unavailable on BSD, but this broke Windows, so I settled for setting _XOPEN_SOURCE=600, which exposed the necessary functions on BSDs.
This no longer works.  libvmaf now uses the non-standard strsep() function, and FreeBSD only exposes non-standard functions if no standards macros are defined — they're purely subtractive.  So if setting _POSIX_C_SOURCE or _XOPEN_SOURCE isn't the right thing to do, what is?  The build error for Windows is due to a missing M_PI macro.  mingw provides this macro if any of the standards macros defined, or _BSD_SOURCE, _GNU_SOURCE, or _USE_MATH_DEFINES.  Since we already set _GNU_SOURCE for Linux, using that for mingw as …

libvmaf: don't set _XOPEN_SOURCE

---

libvmaf/src/cuda/picture_cuda.c
libvmaf/src/feature/cuda/integer_adm_cuda.c
libvmaf/src/feature/cuda/integer_motion_cuda.c
libvmaf/src/feature/cuda/integer_vif_cuda.c

I observed a bunch of errors when compiling vmaf with CUDA enabled. Looks like those errors were exposed when using gcc-14. Running meson with gcc-13 works fine with no issues. This PR fixes errors that prevent me from compiling: explicit casting, missing headers, unused parameter.
Repro:
```
$ meson libvmaf/build libvmaf -Denable_cuda=true -Denable_avx512=true
$ ninja -vC libvmaf/build
```
System:
```
$ cat /etc/redhat-release
Fedora release 41 (Forty One)
```
```
$ gcc --version
gcc (GCC) 14.2.1 20250110 (Red Hat 14.2.1-7)
Copyright (C) 2024 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Fix gcc14 build errors with CUDA enabled

---

Makefile

Numpy is not building in my environment, but I should not need to have it if all I want to build is the default libvmaf target.
Additionally:
Instead of using the mtime of the .venv directory as a marker for whether meson and ninja were successfully installed, use their wrapper scripts from .venv/bin.
The $(VENV) target uses set -e and escaped newlines to run all commands in a single shell invocation. Unless these commands are modifying the shell's environment, this is redundant and mimics the way make already works when you put a single command on each line.

Don't install cythonize dependencies unless cythonizing

---

libvmaf/src/meson.build

Change xxd calls to use '-i' instead of '--include', since the latter is less supported/portable
fixes #1417

In meson.build, change xxd calls for portability (fixes #1417)
